### PR TITLE
Refactor of hydcoeffs.c

### PR DESCRIPTION
**Pull request by LRossman**
Simplifies and unifies how limit on head gradient at low flow is handled.
Avoids generating a Floating Point Overflow error that was causing the EPANET GUI to abort a hydraulic analysis made on at least two different networks.

### CODE REVIEW

**Comment by LRossman** [comment]
The Appveyor (Windows) check fails on the three exnet-3 networks (exnet-3H has a HEADERROR limit,  exnet-3Q has a FLOWCHANGE limit, while exnet-3 has neither). A manual comparison with the benchmark using a Diff utility shows that all pressures and flows agree to 4 decimal places. The status report for exnet-3Q identifies a different max. flow change link than does the benchmark, but the flow change values are the same (the two links are connected to a common node that is one pipe removed from each).

Based on this I propose that we update the Windows benchmark results for the three exnet-3 networks so that this PR can move forward.

**Comment by eladsal** [comment]
Thank you @LRossman, this was a huge effort.

When you say "flow change link than does the benchmark" you mean that it was a different link which is connected to the same junction?

In any case I agree the benchmark results should be updated for these networks.

**Comment by LRossman** [comment]
@eladsal the max. flow change link at Trial 6 in the benchmark is Link 2265 while it's Link 5020 for this commit. For Trial 8 they reverse; 5020 for the benchmark and 2265 for this commit. The numerical values of the max. flow changes are exactly the same. The location of the two links is shown below:
image

I've forgotten the URL where the Windows benchmark files (benchmark-win32-538_1.zip and benchmark-win64-538_2.zip) are located. Do you remember?

**Comment by eladsal** [comment]
Got it, thanks.

The benchmark files are located in the [epanet-example-networks](https://github.com/OpenWaterAnalytics/epanet-example-networks) repo under [releases](https://github.com/OpenWaterAnalytics/epanet-example-networks/releases).

**Comment by LRossman** [comment]
The last commit was made after updating the benchmark results for the three `exnet-3 `networks and revising the Release Notes to reflect the change in how the limit on head loss gradient at low flow is handled.

**Pull request merged**
