### PR TITLE
Removed the EN_DEFDEMANDPAT option

### PR DESCRIPTION
**Pull request by LRossman**
See issue #429. Also allowed the EN_HEADLOSSFORM option to be changed if the solver is not active.

### CODE REVIEW

**Comment by Mariosmsk** [comment]
https://github.com/OpenWaterAnalytics/EPANET/blob/fa4952a265e150721c64d4fb476c8bd8ca55cffb/tests/test_analysis.cpp#L42

I think is
` test.assign(array, array + 12);`

**Comment by eladsal** [comment]
@LRossman thanks, should we consider not changing the constants numbers just in case someone made a mistake and used the numbers? I don't see a problem of not having a number 6.

**Comment by LRossman** [comment]
@eladsal I understand your concern. However, I believe that items 5 - 12 in the `EN_Option` enumeration were added during v.2.2 development. Therefore I consider them all fair game for being modified as need be (in this case removing `EN_DEFDEMANDPAT `and re-numbering the subsequent items so a consecutive ordering is maintained).

@Mariosmsk thanks for spotting the problem in test_analysis.cpp.

@michaeltryby thanks for completing this PR.

**Comment by eladsal** [comment]
@LRossman I agree.

@michaeltryby thanks for the conversation...

**Pull request merged**
