### PR TITLE
node is not a tank

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by LRossman** [comment]
I'm not sure that Error 203 ("undefined node") is best choice to use here. The node passed into the function is actually defined, it's just not a Tank node. A better choice might be Error 209 ("illegal node property value") or better yet, a new error code for "node is not a tank".

**Comment by Mariosmsk** [comment]
Yes, I think a new error would be better.

What do you think about errcode 263?

`DAT(263,"node is not a tank")`

**Comment by LRossman** [comment]
Sounds good.

**Comment by eladsal** [comment]
Any other comment before merging?

**Pull request merged**
