### PR TITLE
code of conduct

### PR DESCRIPTION
**Pull request by samhatchett**
This PR adds a code of conduct, based on the conversation in issue #57 

Please feel free to suggest edits or modifications. This CoC is straight from the template.

### CODE REVIEW

**Comment by eldemet** [comment]
Sam, I've read the text, I think it's good and covers most of the cases. We give an email, I wonder if we need to say explicitly who are the recipients (as it may involve one of the recipients).

**Comment by samhatchett** [comment]
@eldemet brilliant suggestion. Can we modify the text to list The DevCom members?

**Comment by eldemet** [comment]
I can create a separate wiki page with the "Project Maintainers" (Development Committee), and give a link in the text. This way we won't have to update this CoC if we happen to make a change.

**Comment by samhatchett** [comment]
ok, I've roughed out a Project-Team wiki page (hopefully not overlapping efforts with @eldemet). Please anyone edit over there if you want to change that content. Otherwise, ok to merge?

**Comment by eldemet** [comment]
Looks good 👍

**Comment by samhatchett** [comment]
ok, will give this 24h for lazy consensus.

**Pull request merged**
