### PR TITLE
add function ENsetdemandpattern

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by eladsal** [comment]
Thanks @Mariosmsk !
Just a few suggestions:
1. would you mind adding this function to the other header files in the `include` folder?
2. for easier readability it might be better to break the `For` loop at [line 3150](https://github.com/OpenWaterAnalytics/EPANET/pull/86/commits/1b5698a86a3664ba225d7031f6e3ad6717885106#diff-38a911bd86983e691fa46711d21ba3b6R3150).
3. to mach existing code can you add spaces around the assignment of variables, i.e. n = 1 rather than n=1?

**Comment by Mariosmsk** [comment]
Hello Elad,

Regarding your suggestions:
1. I will do it.
2 & 3.  Actually the same formatting was for the ENsetbasedemand! I think we should fix these readability issues on a different commit :-)

**Comment by eladsal** [comment]
Fine by me. Anyone else?

**Comment by eladsal** [comment]
The dll crash @Mariosmsk mentioned accrued when the `demandIdx` was larger than the number of demand categories.

@Mariosmsk, I see how the use of the `ENgetnumdemands` function helps but I wonder if we need these two loops over the demand categories (on in the original function and one in `ENgetnumdemands`). Maybe there is a way to change the stopping criteria.

As I side note, I have noticed that the Toolkit doesn't load (and saves) the categories names. Hope we can make that happen.

**Comment by samhatchett** [comment]
wow, how horrible that we left this PR to languish for so long. sorry @Mariosmsk !! 

I will look at this in more detail in the coming week and we will get this merged soon.

**Comment by Mariosmsk** [comment]
I have updated the code. So I close that PR and open new.

**Pull request closed without merging**
