### PR TITLE
Feature unittest

### PR DESCRIPTION
**Pull request by michaeltryby**
Closes Issue #152

### CODE REVIEW

**Comment by michaeltryby** [comment]
With this PR unit testing and regression testing are operational on both Appveyor and Travis CI servers. Tests are running but failing.

**Comment by michaeltryby** [comment]
@samhatchett this PR includes changes to CMakeLists.txt that you may want to review prior to merge. Please have a look at your earliest convenience. Thanks! :smile:

**Comment by michaeltryby** [comment]
The biggest change to cmake is the inclusion of generate export header which is needed to link the epanet.dll into the SWIG wrapper instead of recompiling the library in it's entirety.

**Comment by eladsal** [comment]
@michaeltryby what is the nature of the change in `epanet2.h`?

**Comment by michaeltryby** [comment]
@eladsel cmake automatically generates epanet_export.h depending on what platform (Windows, Linux, Mac) you are building on. It also automatically creates the export library needed at link time to use the epanet.dll on Windows.

**Comment by eladsal** [comment]
Does it create and link the DEF file as well?

**Comment by michaeltryby** [comment]
Cmake creates the export library so we no longer need to maintain a .def file to link with the dll on Windows.

**Comment by eladsal** [comment]
What do you mean by the "export library"?
Can you please send me the latest dll you compiled?

**Comment by michaeltryby** [comment]
Here is an MSDN article that describes the process. https://msdn.microsoft.com/en-us/library/windows/desktop/ms682592(v=vs.85).aspx

**Comment by michaeltryby** [comment]
The article describes the file as an import library sorry for the confusion calling it an export library. Anyhow it is used instead of the .def file.

**Comment by eladsal** [comment]
I don't see a reference to the size of the functions variables (in bytes) like there was in the DEF file.

This change of the `epanet2.h` file is the only core file change in this PR and so if I could test the DLL you build without having now to learn how cmake works and how to use the cl compiler with it would save me some time. (sorry for the long sentence).

**Comment by michaeltryby** [comment]
@eladsal I'm on an iPhone right now so it will have to wait. Surely you must have Visual Studio installed? Have you ever used the msbuild command prompt that comes with Visual Studio? CMake is used to generate the msbuild command files and then it calls msbuild to build. The instructions for using cmake are in the header of the CMakeLists.txt file.

**Comment by michaeltryby** [comment]
@eladsal I encourage you to try using cmake to build the project. The learning curve is signicant but the convenience is worth it. :smile:

**Comment by eladsal** [comment]
No, actually I don't have Visual Studio istalled, just the parts which comes with the .NET framework. CMakes output is: "could not find any instance of Visual Studio".
Since you say that the CMake script should work fine I'd really appriciate if you can send me the Windows 32 bits DLL it produced so I can validate it before we move ahead with a PR which changes the way we compile EPANET, thanks!

**Comment by michaeltryby** [comment]
@eladsal I will prepare step-by-step instructions on building the project from source and post them for the benefit of the community. I will let you know when they are live.

**Comment by michaeltryby** [comment]
@eladsal and @samhatchett I'd like to more forward with this PR. I've provided the build instructions I promised in a separate email addressed to you and @bemcdonnell. 

My vote is to accept and merge this PR and tackle the cmake def file in another issue. Sound good?

**Comment by michaeltryby** [comment]
Abandoning this PR. It combines to many issues and creates a backward compatibility problem for Elad. I will separate the issues and resubmit them individually.

**Comment by eladsal** [comment]
@michaeltryby if we just keep the `epanet2.h` header file without changes we can have both build scripts until we sort this issue out.

**Comment by michaeltryby** [comment]
@eladsal it's okay. Making the change over to using generate_export_header isn't necessary for unit testing. I was squeezing it in here and it was causing problems. It will be cleaner to handle it separately. It was good to get the build documentation written too! No worries :smile:

**Pull request closed without merging**
