### PR TITLE
Migrating to benchmark 2012vs10

### LINKED ISSUE #170: Update Benchmark to epanet v2.0.12 compiled with Visual Studio 10 2010
The current epanet benchmark is v 2.0.12 compiled using Visual Studio 6.  As discussed in Issue #129, it has been discovered that the failing reg tests on Appveyor can be attributed to differences in results attributed to the SUT epanet v2.2.0dev being compiled with Visual Studio 10 2010. 

Therefore, we should update the benchmark and bring the repo into a passing state so we can begin taking full advantage of the reg testing framework. We can follow-up by discussing which compiler version to port to and fine tuning compiler settings to improve agreement between VS6 and VS10. Thoughts?

### PR DESCRIPTION
**Pull request by michaeltryby**
Closes #170 

Badge is now green on Appveyor!

### CODE REVIEW

**Comment by michaeltryby** [comment]
Tests are passing on Appveyor and operational but failing on Travis.

**Comment by samhatchett** [comment]
really great, @michaeltryby - do you think it's likely or possible that the regression errors on Travis are just due to compiler differences, as we saw here?

**Comment by michaeltryby** [comment]
Thanks @samhatchett! 

Yes, I think there is a high likelihood that the reg test failures on Travis can also be attributed to compiler differences.

**Comment by samhatchett** [comment]
so then the question becomes, how to surface what the problem might be - if it is actually a problem, if the numerical differences are actually non-negligible.

**Comment by michaeltryby** [comment]
Yeah, I agree. Recommend examination of the differences and try to minimize them through judicious selection of compiler settings. Then establish a Linux benchmark.

**Pull request merged**
