### PR TITLE
Pressure Dependent Demands added to address issue 163

### PR DESCRIPTION
**Pull request by LRossman**
Pressure Driven Analysis (PDA) was added as an alternative to EPANET's traditional Demand Driven Analysis (DDA) to avoid situations where demands are delivered at negative pressure. More description of how PDA was implemented is contained in the draft Release Notes for EPANET 2.2 which is also included in this PR. The new PDA option has been successfully tested against Example 1 in the paper by [Cheung et al. 2005](https://www.researchgate.net/publication/228570015_Extension_of_epanet_for_pressure_driven_demand_modeling_in_water_distribution_system) although the method used here is different from that in the paper.

### CODE REVIEW

**Comment by michaeltryby** [comment]
@LRossman Looks great! 👍

**Comment by hitdongfeng** [comment]
looks great!

**Comment by eladsal** [comment]
@LRossman, any particular reason you removed the [checks](https://github.com/OpenWaterAnalytics/EPANET/pull/210/files#diff-f28e20c240cc0279a5e4069fd885861aL621) I add when saving the new parameters to the INP file? Maybe your local code wasn't up to date with the `dev` branch? If it wasn't intentional I will add them back.

**Comment by michaeltryby** [comment]
@eladsal curious why you added the checks in the first place? To help preserve backward compatibility?

**Comment by eladsal** [comment]
Exactly. 
https://github.com/OpenWaterAnalytics/EPANET/commit/f86df2291a12003c9ba05f56fbc574db5bbe8f3c

**Comment by michaeltryby** [comment]
@eladsel I understand your motivation to help preserve backward compatibility. I agree that it’s important. Perhaps there is a better way to do it?

**Comment by LRossman** [comment]
@eladsal I don't remember why I removed your checks in _inpfile.c_, but clearly since I added checks for the new PDA parameters there should also be checks for the two new convergence parameters. You can add them (or I can on the next build since I see that the regression tests failed on two files which I will have to resolve).

@michaeltryby these "checks" merely skip writing the new parameters to a new INP file created by _inpfile.c_ when they are at their default values which will maintain backwards compatibility for previous apps that won't be updated to include the functionality they represent. I don't see a need to modify the input file parser based on API version since if these parameters don't appear in the file they are assigned default values that has them ignored.

**Comment by michaeltryby** [comment]
@LRossman Instead of an ad hoc approach I propose an alternative where we version the input format and explicitly engineer the parser for backward compatibility. That’s the idea.

**Comment by eladsal** [comment]
@LRossman the two networks which are failing don't report the `maximum  flow change` value. I think this is due to the setting of `maxflowlink ` to -1 at `newdemandflows` and\or `newemitterflows`. When removing this setting the message is reported. However, now I see some differences in the `maxflowchange` values.

Hope this helps and that I understood the code flow correctly.

**Comment by eladsal** [comment]
@LRossman I was trying to resolve some conflicts with my commit and I may have something wrong with the conflict editor. I'm sorry if I messed something with your code. If so I'll might need a GH expert to help with this (@samhatchett).

**Comment by LRossman** [comment]
@eladsal thanks for finding the cause of the reg test failure for the two networks containing an emitter node. If the max. flow change for a hydraulic solution occurs at either an emitter node or a pressure driven demand node, then` hbal.maxflowlink` is set to -1 and `hbal.maxflownode` is set to the node's index. When the max. flow change is listed in the _Status Report_, either a node or link ID should be reported, depending on which of `maxflowlink` and `maxflownode` is >= 1. The current code only checks `maxflowlink`. A check for `maxflownode` will be added in a new commit shortly. Even so, the reg tests on the emitter networks will likely still 'fail' since the previous dev build didn't consider nodal outflows when reporting a max. flow change.

**Comment by eladsal** [comment]
@LRossman I have ran my test script and you are right, there is still a difference in the report files with the maximum flow change values. However, **all** the reported results are exactly the same.

**Comment by michaeltryby** [comment]
@LRossman Are there any new tests you would like to add to the reg test suite?

**Comment by LRossman** [comment]
@michaeltryby I don't have any new files for the reg test suite right now. If possible, could you eliminate comparing the contents of the Status Report in your tests since this has caused past failures due to harmless formatting changes. Can we just stick to comparing the numerical contents of the binary results file?

**Comment by michaeltryby** [comment]
@LRossman so let me get this straight. You and @eladsal literally just used reg testing comparison of the output files to identify and fix a bug in a status report and you are requesting that I eliminate comparison of status reports? Really? Cause from my perspective it just served its purpose.

**Comment by eladsal** [comment]
@michaeltryby how did I get into your comment? I only wrote that the report files are different while the output results are the same. How would one understand from that comment that we need to drop this test?

@LRossman: its not only formatting changes.

**Comment by milad-ghiami** [comment]
@LRossman  it great :)

**Comment by michaeltryby** [comment]
@LRossman I need a reg test to more forward on this. Thanks!

**Comment by LRossman** [comment]
@michaeltryby see this file. 
[Cheung.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2314654/Cheung.txt)

**Comment by michaeltryby** [comment]
Testing is operational. Appveyor 32 bit benchmark is passing. 
This PR is good for merge.

**Comment by michaeltryby** [comment]
Nice work Lew! :smile:

**Comment by eladsal** [comment]
@michaeltryby was there a change in the base version for the testing with this PR? I don't see anything the commits that fixes the failing testing reported and they still fail for me. What am I missing?

**Comment by michaeltryby** [comment]
@eladsal to reduce repo clutter rhe benchmark artifacts, the report files and binary output files, aren’t actually checked in. Only the input files used to generate them are. 

I updated the input files, and then ran the tests locally. Generating the new benchmark artifacts. Then I zip them up and upload the zip archive to a new tagged release I created in the epanet-example-networks repo. 

A release has a stable URL where the files can be found. The before-tests script uses the benchmark url. In the commits above I updated the scripts with the new benchmark version. 

A little complicated but that’s how I did it.

**Comment by eladsal** [comment]
@michaeltryby I understand your workflow but my question is with which version of the code did you produce the new report and binary files? I ask this since for all networks besides the new `cheung` one we should have the same results, and we don't.

**Comment by michaeltryby** [comment]
@eladsal I built this PR.

**Comment by eladsal** [comment]
@michaeltryby So how do we explain the difference in the report file of `Net1emit` which should not have changed in this new code?
Previous report file:
 `maximum  flow change = 0.0733 for Link 110p`
New report file:
`maximum  flow change = 0.0734 for Node 23`

**Comment by michaeltryby** [comment]
@eladsal I was only aware of two failing tests Net1emit and Net1negemmit. Are these the differences in results you are referring to or am I missing something.

**Comment by eladsal** [comment]
@michaeltryby Yes, these files. Are we ignoring these differences?

**Comment by eladsal** [comment]
@michaeltryby  One more thing, should we tag the current version of the code as a "benchmark change" (or maybe you already done so)? Otherwise we might never be able to reproduce the output files again.

**Comment by michaeltryby** [comment]
@eladsal Lew changed status reporting behavior as part of this PR. Your discussion with him about it can be found immediately above.

**Comment by eladsal** [comment]
@michaeltryby OK, I didn't understand that this was resolved as the report seems different in [values](https://github.com/OpenWaterAnalytics/EPANET/pull/210#issuecomment-415967808). not only formatting (as I stated [above](https://github.com/OpenWaterAnalytics/EPANET/pull/210#issuecomment-414072666)).

**Comment by michaeltryby** [comment]
There are two branches in the epanet-examples-network master and dev-rolling. These changes are part of the rolling benchmark to maintain reg testing on CI as we develop. When we release we will create a master benchmark. We can use the releases there to help keep track of all this stuff.

**Comment by michaeltryby** [comment]
@eladsal are there changes in the binary results on these two tests? I suppose you could raise an issue about it and we can get to the bottom of it.

**Comment by eladsal** [comment]
Why not tag it in this repo so we have the EPANET snapshot of the code? This is a sensitive moment in the development cycle when we say that the benchmark changed and we are doing this knowingly.

As for the two files, there are no changes in the binary results.

**Comment by eladsal** [comment]
@michaeltryby I understand that you are fine with the change. I'm saying that the benchmark has changed and no one can tell this from the repo or from the discussion here (well, now they can..)

**Comment by michaeltryby** [comment]
@eladsal I’m not to concerned. You are welcome to tag it if you would like to.  Something with a dev2 on the end would be fine.

**Comment by eladsal** [comment]
I will post a draft Tag and we can decide. Thanks!

**Comment by michaeltryby** [comment]
All binary files produced are the same and two report files have a status report message with a flow change difference in the 4th decimal place. These benchmarks are 99.999% identical.

**Comment by eladsal** [comment]
@michaeltryby true. Please note that the flows reported are for different elements, Link 110p and Node 23.

I have created a draft Tag but not sure it is public, can you please verify? Thanks

**Pull request merged**
