### PR TITLE
Fixes zero flow (#164) and D-W eqn. (#199) issues

### PR DESCRIPTION
**Pull request by LRossman**
This update corrects the way that EPANET deals with flows that approach zero to avoid making its hydraulic solution matrix ill-conditioned. It also correctly accounts for the derivative of the friction factor w.r.t. flow when using the Darcy-Weisbach head loss formula. As a result of these changes the correct solution to the GESTAR1.INP and GESTAR1MOD.INP networks are now obtained (v. 2.0/2.1 produced incorrect solutions) and fewer trials are needed to solve D-W models.

These changes will result in slightly different results for the regression test suite. In the larger models, flow differences beyond the second decimal place occur for about 20% of the links. The accuracy values tracked in the Status Report will also show slight differences in most of the models. Examining results from 16 of the reg test models did not reveal any radical differences from those for the current `dev` branch (with the exception of two GESTAR networks as noted above).

Closes Issue #164
Closes Issue #199

### CODE REVIEW

**Comment by michaeltryby** [comment]
@LRossman Nice work!

**Comment by LRossman** [comment]
Latest commit provides a more robust method for handling near-zero flows to prevent the hydraulic solution matrix from becoming ill-conditioned. Earlier comments regarding the reg tests still apply.

I would be happy to provide more explanation of the method being used if anyone would like to see it instead of  trying to glean it from the code (just let me know the appropriate landing spot to place it).

**Comment by samhatchett** [comment]
@LRossman if you'd like to document the method in more detail, you could add a DOXY file, similar to that seen here:
https://github.com/OpenWaterAnalytics/EPANET/blob/dev/doc/How-to-use-the-toolkit.dox

... and link it in to the main documentation using `@subpage` like this:
https://github.com/OpenWaterAnalytics/EPANET/blob/756e8be735f853d319d2eb2fe303a8eb22339500/doc/Toolkit-Overview.dox#L21

**Comment by michaeltryby** [comment]
@LRossman do you have any regression tests accompanying this PR that you would like to add to the test suite?

**Comment by LRossman** [comment]
@michaeltryby the suite already contains gestar1.inp and gorev2.inp for which v. 2.0/2.1 gives the wrong flow results whereas this commit, with its more rigorous handling of low flow conditions,  produces the correct flow values (see [Estrada et al., 2009](https://ascelibrary.org/doi/full/10.1061/%28ASCE%29IR.1943-4774.0000100) and [Gorev et al., 2013](https://ascelibrary.org/doi/10.1061/%28ASCE%29HY.1943-7900.0000694)). Gestar1.inp and jep5-13.inp illustrate the improved convergence rate obtained by fixing the D-W gradient calculation. Gestar1 required 21 trials under v. 2.0/2.1 but only 9 trials with this new update. For jep5-13 it was 22 trials v. 18.

**Comment by michaeltryby** [comment]
@LRossman actually the test suite does not contain gorev2.inp. Can you please send it along so I can add it. Thanks!

**Comment by LRossman** [comment]
[Gorev2.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2379775/Gorev2.txt)

**Comment by michaeltryby** [comment]
This PR is good for merge.

**Comment by eladsal** [comment]
@michaeltryby with this PR merge we are changing the tests baseline, right?

**Comment by michaeltryby** [comment]
@eladsal Yes the rolling dev benchmark has been updated. I am maintaining two benchmarks. One for the master branch and one for the dev branch. The master benchmark gets updated when we release. The dev benchmark rolls along with development so we can have the benefits of CI while we work. Make sense? 

After I merge this can you do me a favor and tag the OWA/epanet dev branch "v2.2.0-dev.3". Sound good?

**Comment by eladsal** [comment]
Yes, I will Tag it. This is why I asked.

**Pull request merged**
