### PR TITLE
try to fix bug in EN_getdemandname

### PR DESCRIPTION
**Pull request by Mariosmsk**
#430

### CODE REVIEW

**Comment by Mariosmsk** [comment]
I have replaced `MAXMSG ` with `MAXID `and I have added a check if demandName is too long in `EN_setdemandname`.

**Comment by michaeltryby** [comment]
@Mariosmsk  a test would be a great addition to this PR.

**Comment by michaeltryby** [comment]
@Mariosmsk Nice!

**Comment by Mariosmsk** [comment]
Can someone please merge this PR?

**Comment by michaeltryby** [comment]
@Mariosmsk Looks like there are some merge conflicts. Could you fetch pull OWA/epanet:dev and resolve them?

**Comment by michaeltryby** [comment]
@Mariosmsk I resolved these conflicts in your branch. You need to merge them there then I can merge here.

**Pull request merged**
