### PR TITLE
Msg overflow

### PR DESCRIPTION
**Pull request by bradleyjeck**
Dear Maintainers,

The changes in this PR were made to pass checks required of compiled C code in R packages. I submit it here for possible inclusion in the next release of EPANET.

In a few cases it is possible for a string message to overflow the buffer. This PR fixes the issue by shortening a few messages and in one case providing a longer buffer. Another alternative would be to increase the buffer size for all messages.

### CODE REVIEW

**Comment by eladsal** [comment]
@bradleyjeck:
You propose to make a larger buffer for FMT54 and FMT55 and at the same time to shorten FMT54. If we use a longer message is there still a need to shorten FMT54?

I don't understand how but I'm getting longer messages than Msg written to the report file for FMT54. For example 90 chars:
"Pump 999999999999999999999999999999 changed by Tank 222222222222222222222222222222 control"

**Comment by bradleyjeck** [comment]
@eladsal: 
I agree it's not the most consistent solution.  I initially tried to shorten the messages to avoid creating the buffer LongMsg, but decided in the case of controls there was a possibility to lose too much info. So I added LongMsg anyway.  As noted above increasing all the buffer sizes would also work.

In my understanding the underlying issue is one of security rather than performance.  sprintf doesn't check length so anything can be written.   A better solution is probably to use snprintf instead.

Some further reading is here: https://www.cprogramming.com/tutorial/secure.html

I'll dig out the warning message I was getting from R that caused this change.  Might be tomorrow.

**Comment by eladsal** [comment]
The fact that currently longer than 80 chars messages are written to the report file gives me some comfort in officially making the messages longer. Not sure we need to go with 80*2 long but it should be easy to calculate the longest message since the nodes\links IDs are maxed. Probably 100 chars will do.

**Comment by bradleyjeck** [comment]
Agree that the message lengths can and should be bounded.  It also seems like the 11 uses of sprintf in the code should change to use snprintf instead.  Should we open a new issue for that?

**Comment by eladsal** [comment]
> It also seems like the 11 uses of sprintf in the code should change to use snprintf instead. Should we open a new issue for that?

Sure

**Comment by michaeltryby** [comment]
Any objections to merging this?

**Comment by samhatchett** [comment]
Seems like a simpler option is just to increase the size of the buffer `Msg[MAXMSG+1]`. Then we wouldn't have to introduce strange spelling and make the formatted messages even more cryptic. Looking back over the history of other branches, I think this is why the definition of `MAXMSG` was increased from something tiny to something more reasonable (unintentionally breaking the binary file format).

What about that option? Increase `MAXMSG` to something reasonable, and remove its usage in `output.c`? That's probably the least invasive approach.

**Comment by bradleyjeck** [comment]
Agree that increasing the size of the buffer for all the messages is the most straightforward way to go.

**Comment by eladsal** [comment]
I agree. `MAXMSG` is only used in `output.c` to [write](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/output.c#L80) the title of the project. I suggest to add a new constant for that, maybe `MAXTITLE` as these are two separate string.

**Comment by samhatchett** [comment]
closed in favor of #189

**Pull request closed without merging**
