### PR TITLE
Feature wrapper

### PR DESCRIPTION
**Pull request by samhatchett**
wow, another large PR. This will merge the "wrapper" feature into `dev`, which looks like a big deal, but it really just wraps all of EPANET's global variables into a couple of structs that get passed around. This ends up duplicating the API, giving you an additional thread safe function for each original function. For instance:

`ENgetnodevalue(....`

becomes:

`EN_getnodevalue(EN_Project *p, ...`

### CODE REVIEW

**Comment by samhatchett** [comment]
feel free to review - although as @michaeltryby has commented, we should also focus on fixing the regression tests. I am working through that, and will push fixes to this PR, prior to merging into `dev`.

**Comment by eladsal** [comment]
I'm getting many compile errors. I think some are due to variables not being declared at the headers of the function

input2.c(399) : error C2065: 'curve' : undeclared identifier
input2.c(400) : error C2065: 'curve' : undeclared identifier
input2.c(400) : error C2223: left of '->Npts' must point to struct/union
input2.c(403) : error C2065: 'curve' : undeclared identifier
input2.c(403) : error C2223: left of '->X' must point to struct/union
input2.c(404) : error C2065: 'curve' : undeclared identifier
input2.c(404) : error C2223: left of '->Y' must point to struct/union
input2.c(408) : error C2065: 'curve' : undeclared identifier
input2.c(408) : error C2223: left of '->X' must point to struct/union
input2.c(411) : error C2065: 'curve' : undeclared identifier
input2.c(411) : error C2223: left of '->Y' must point to struct/union
input2.c(412) : error C2065: 'curve' : undeclared identifier
input2.c(412) : error C2223: left of '->X' must point to struct/union
input2.c(413) : error C2065: 'curve' : undeclared identifier
input2.c(413) : error C2223: left of '->Y' must point to struct/union
input2.c(414) : error C2065: 'curve' : undeclared identifier
input2.c(414) : error C2223: left of '->X' must point to struct/union
input2.c(415) : error C2065: 'curve' : undeclared identifier
input2.c(415) : error C2223: left of '->Y' must point to struct/union
input2.c(427) : error C2065: 'link' : undeclared identifier
input2.c(427) : error C2223: left of '->ID' must point to struct/union
input2.c(448) : error C2065: 'link' : undeclared identifier
input2.c(448) : error C2223: left of '->ID' must point to struct/union
input2.c(622) : error C2143: syntax error : missing ';' before 'type'
input2.c(623) : error C2065: 'errMsg' : undeclared identifier
input2.c(623) : warning C4047: 'function' : 'char *' differs in levels of indire
ction from 'int'
input2.c(623) : warning C4024: 'EN_geterror' : different types for formal and ac
tual parameter 2
input2.c(624) : error C2065: 'errMsg' : undeclared identifier
input3.c
input3.c(73) : error C2143: syntax error : missing ';' before 'const'
input3.c(93) : error C2275: 'Snode' : illegal use of this type as an expression

**Comment by samhatchett** [comment]
@eladsal  what is your compiler?

**Comment by eladsal** [comment]
Microsoft cl

I think this is reacquired by C89 compilers which the current code base follows.

**Comment by samhatchett** [comment]
can you turn on C99 support or use the C++ compiler? Suppose we could change the code, but this variable declaration stuff is not really that uncommon. Boo.

**Comment by eladsal** [comment]
> can you turn on C99 support or use the C++ compiler?
Well, not currently with the procedures I have and know. Also not sure that the other errors are related.

**Comment by eladsal** [comment]
What is the M_PI replacement for PI in types.h? Currently it is not defined as PI and raising an error

**Comment by samhatchett** [comment]
looks like that's another C89 issue:

```
#ifndef M_PI
  #define M_PI 3.14159265358979323846
#endif
```

**Comment by samhatchett** [comment]
oh, that should be an `ifdef`, not an `ifndef`:

```
#ifdef M_PI
  #define PI M_PI
#else
  #define   PI        3.141592654
#endif
```

**Comment by eladsal** [comment]
I think in getTmpName (epanet.c) TmpDir is not declared well. Should be something like p->out->TmpDir. Probably the function should get the project as a input.

**Comment by michaeltryby** [comment]
@samhatchett I have started modifications to feature-wrapper for SWIG and I have been working on getting appveyor working which is dependent on the nrtest stuff located here. I need a place for this work, so I am fine with merging and fixing what breaks. Sound good?

**Comment by samhatchett** [comment]
good with me - I know also that @eladsal has been working through some breaking changes, but we're essentially committed to this extended api -  so we'll just focus the work on fixing things and getting windows CI working within `dev`

**Comment by michaeltryby** [comment]
@samhatchett This feature-wrapper PR was a heavy lift.  Great work!

**Comment by eladsal** [comment]
Great, thanks. Maybe you can also merge #140 which should be much simpler compared.

**Comment by eladsal** [comment]
@samhatchett I think some older commits are now missing in `dev`, for example the [option to retrieve the pumps price pattern](https://github.com/OpenWaterAnalytics/EPANET/commit/8ab0f06ccc4c28631738b43fd5dbe91ad71c1c28)

**Comment by samhatchett** [comment]
@eladsal if you find anything else, please let me know. this was messy.

**Comment by eladsal** [comment]
Will do, started to make some manual checks :(

**Pull request merged**
