### PR TITLE
Update AUTHORS file - organize by release and order alphabetically

### PR DESCRIPTION
**Pull request by rjanke20**
I updated the AUTHORS file in my dev branch at https://github.com/rjanke20/EPANET.

### CODE REVIEW

**Comment by rjanke20** [comment]
Thanks!  I am just beginning to learn how to use Github. It didn't seem to like this pull request.

**Comment by rjanke20** [comment]
Thanks!  I am just beginning to learn how to use Github. It didn't seem to like this pull request.

**Comment by eladsal** [comment]
This PR is failing the build tests.

**Comment by samhatchett** [comment]
there were some conflicts - I've resolved them manually so we should get to CI in a few minutes.

**Comment by rjanke20** [comment]
The conflicts were my fault, sorry!


On Dec 13, 2019, at 2:52 PM, Sam Hatchett <notifications@github.com> wrote:

﻿

there were some conflicts - I've resolved them manually so we should get to CI in a few minutes.

**Pull request merged**
