### PR TITLE
Let the os handle temporary files

### PR DESCRIPTION
**Pull request by AbelHeinsbroek**
The littering of temporary scratch files generated by multiple instances running at the same time, or of improperly closed instances, were driving me nuts. I propose having the OS handle the creation and subsequent removal of scratch files using the ```tmpfile``` library function. 

A big advantage is that the scratch files get automatically removed, even if the process quits unexpectedly.

### CODE REVIEW

**Comment by samhatchett** [comment]
I see that Windows' `tmpfile` is deprecated in favor of the more-secure [`tmpfile_s`](https://docs.microsoft.com/en-us/previous-versions/b3dz6009%28v%3dvs.140%29). And we are still limited to `TMP_MAX_S` number of files. So I'm not completely sure what this buys us? The auto-cleanup is nice, but I wonder if there's a more elegant solution?

In the future, I think it would be great to associate new PRs with existing issues that reflect some level of discussion about changes in the code or execution behavior. This is a nice PR, understand - but the underlying motivation and implementation probably needs some discussion/banter.

**Comment by AbelHeinsbroek** [comment]
I created this PR because I saw that the latest EPANET 2.2 builds were littering my filesystem with temporary files when not closed correctly, which can easily happen when iteratively developing networks in a tool such as Jupyter. In investigating the issue I accidentally already came up with a solution for it, thus choosing not to make a duplicate PR and issue.

Though its true that we're limited by TMP_MAX, this value is of such a big size (2147483647 or INT_MAX on Windows) that it's unlikely we'll ever be running into this limit in practice. I prefer using this function over generating temporary files ourselves as this not only ensures that the temporary files get removed properly, but that they are also placed inside the correct location (/tmp, /var/tmp, %TEMP%) etc. I'll look into using ```tmpfile_s``` instead of ```tmpfile```.

Perhaps the most elegant solution would be to forego using scratch files altogether, but I'm not familiar with the EPANET solver to know whether that would be a viable option.

**Comment by LRossman** [comment]
On Windows both `tmpfile() `and `tmpfile_s()` create files in the root directory. Some networked/corporate environments don't allow users to access the root directory on their machines (that was true at EPA where I used to work). So aside from security, this possibility makes `tmpfile()` a nonviable option in my opinion.

Is there some way you could make your Jupyter app more aware of the need to properly close down the EPANET toolkit?

**Comment by samhatchett** [comment]
I agree with @LRossman - in addition to the corporate environment problem, as a Mac user I know that I've encountered problems with libraries attempting to write files outside of the user's authorized scope. Probably better to cleanup separately. There may even be good reasons to collect temp files after an unclean exit, for examination.

I respectfully vote to close this PR without merge.

**Comment by AbelHeinsbroek** [comment]
I agree with your comments on my suggested implementation using tmpfile and tmpfile_s. 
I would still however like to come up with a more elegant/standard solution to handling temporary files. I'll open an issue to discuss some possibilities.

**Pull request closed without merging**
