### PR TITLE
Made mempool.c threadsafe (#234)

### PR DESCRIPTION
**Pull request by LRossman**
The memory pool module (`mempool.h` and `mempool.c`) was re-written to make it re-entrant and thread safe. Updates to `quality.c,` the only place where mempool functions are called, were also made to accommodate the re-written module. And a small change was also made to` types.h` using a forward reference to the mempool struct instead of #including `mempool.h`.

In addition, edits were made to the draft 2.2 Release Notes so that the pressure dependent demand equation appears correctly since the GitHub markdown renderer doesn't recognize LaTeX math tags.

### CODE REVIEW

**Comment by LRossman** [comment]
@michaeltryby here is a test I ran which produced correct results:
```
// Thread safe test of mempool running net1.inp in two separate threads
// concurrently. The two resulting report files should be identical.

#include "epanet2.h"
#include <omp.h>

int main()
{
    int i;
    EN_ProjectHandle ph[2];

    EN_createproject(&ph[0]);
    EN_open(ph[0], "net1.inp", "net1a.rpt", "");
    EN_createproject(&ph[1]);
    EN_open(ph[1], "net1.inp", "net1b.rpt", "");

#pragma omp parallel num_threads(3)
{
    #pragma omp for
    for (i = 0; i < 2; i++)
    {
        EN_solveH(ph[i]);
        EN_solveQ(ph[i]);
        EN_report(ph[i]);
        EN_close(ph[i]);
        EN_deleteproject(&ph[i]);
    }
}
    return 0;
}
```
P.S. I added a `NODES ALL` line to the [REPORT] section of net1.inp in the repo's _tests\data_ folder so there would be some numbers to compare.

**Comment by michaeltryby** [comment]
The segfaults that I observed occured intermittently.

**Comment by michaeltryby** [comment]
@LRossman Nice work! 

I am going to commit some changes to add a unit test and then merge this PR.

**Comment by michaeltryby** [comment]
This PR is good for merge.

**Comment by eladsal** [comment]
@michaeltryby when the test is running, where can you see the outputs from `test_reent.cpp`?
For example: `printf("Thread #%ld EPANET done. Status = %d\n", i, errorcode);`

**Comment by michaeltryby** [comment]
@eladsal you can see pass/fail results in the CI server logs. Or if you run it locally and see the messages it prints to stdout.

**Comment by eladsal** [comment]
@michaeltryby is there a way to print something to the CI console?

**Comment by michaeltryby** [comment]
@eladsal No not that I know of. The stream stdout is captured by ctest and redirected it to a log file.

**Pull request merged**
