### PR TITLE
Feature nrtest

### PR DESCRIPTION
**Pull request by michaeltryby**
Addresses Issue #97. It wasn't pretty, but `nrtest` is now running from Travis CI. 

Note that the tests are failing, however, `nrtest` is running properly. Testing identifies differences in water quality results between the EPANET v 2.0.12 reference and the current build.

### CODE REVIEW

**Comment by bemcdonnell** [comment]
@michaeltryby, Awesome work!

**Comment by michaeltryby** [comment]
Suggest doing a squash and merge on this one!

**Comment by michaeltryby** [comment]
Review of pull requests is a great way to learn and improve the quality of our work. If @samhatchett is too busy perhaps another member of the dev committee could review this. Sound good?

**Comment by bemcdonnell** [comment]
@michaeltryby, do you think there might be value in adding more tests?

**Comment by michaeltryby** [comment]
@bemcdonnell Yeah I agree that more tests would be good. I asked @LRossman if he would contribute his bench marking library. Waiting to hear back from him.

**Comment by samhatchett** [comment]
@michaeltryby as you know, i've been on vacation all last week. Thus the delay. 

Of course anyone else is welcome and encouraged to add their review as well, but I intend to look this over in the next 4-5 days.

**Comment by michaeltryby** [comment]
Thanks @samhatchett!

**Pull request merged**
