### PR TITLE
add ENsetdemandpattern

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by Mariosmsk** [comment]
We tried to add again before (#86)

**Comment by michaeltryby** [comment]
We have a unit testing framework in place. We should be writiing unit tests when we add new api functions.

**Comment by Mariosmsk** [comment]
@michaeltryby, where I can find an example? I have tested the function via Matlab.

**Comment by bemcdonnell** [comment]
@Mariosmsk, here is a simple example to test API mechanics for a rain gage precipitation setters in SWMM: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/tests/test_toolkitapi_gage.cpp

**Comment by eladsal** [comment]
@Mariosmsk when all parameters are legal the functions works well. However, when trying to set `demandIdx` larger by 1 from the node's total number of demands the DLL crashes instead of returning 253. I see you are using the check taken from `EN_getdemandpattern` so I checked that function and it also crashes.

**Comment by Mariosmsk** [comment]
Aso the functions EN_setbasedemand, EN_getbasedemand. My old solution is here https://github.com/OpenWaterAnalytics/EPANET/pull/86/commits/55a98d450c80218da61c1d55adc85438853a05f4

But I use the function EN_getnumdemands. It's ok?

**Comment by eladsal** [comment]
Using `EN_getnumdemands` should work but it means that we loop twice over the demands. Maybe changing the condition to:
`for (d = Node[nodeIndex].D; n < demandIdx && d->next != NULL; d = d->next)`

**Comment by Mariosmsk** [comment]
Yes. it's good! Thanks!

**Comment by eladsal** [comment]
Now it works.

So this PR fixed also `EN_getbasedemand`, `EN_setbasedemand` and `EN_getdemandpattern`  - Great!

**Comment by michaeltryby** [comment]
Looks great! Please remember to add unit tests before merging.

**Comment by eladsal** [comment]
Test add, thanks @Mariosmsk. Seems we are good to merge...

**Comment by michaeltryby** [comment]
@eladsal and @Mariosmsk If you look at the Travis CI. This PR breaks the build on Linux and therefore should not have been merged.

**Comment by michaeltryby** [comment]
Even though the Linux build is failing you still need to check it.

**Comment by eladsal** [comment]
If this PR breaks the Linux build why don't I see the same issue with `dev`?

**Comment by eladsal** [comment]
But dev doesn't fail the build?

**Comment by michaeltryby** [comment]
Cause I fixed the error in a subsequent PR.

**Comment by eladsal** [comment]
@michaeltryby sorry but you are talking with hints. I can't follow you :(

**Comment by michaeltryby** [comment]
No worries :smile: I'll fix it!

**Pull request merged**
