### PR TITLE
Add test cases

### PR DESCRIPTION
**Pull request by michaeltryby**
Adding various regression testing cases for EPANET. A total of 45 tests are now available.

### CODE REVIEW

**Comment by michaeltryby** [comment]
Regression testing on AppVeyor and Travis is operational but failing.

**Comment by samhatchett** [comment]
This is great, @michaeltryby - more benchmarks are really helpful. Two questions:
- are the text report files needed for the tests?
- any ideas as to why the regression is failing?

**Comment by michaeltryby** [comment]
Hey @samhatchett! 

Within the python package nrtest-epanet there are comparison routines for the binary output files and the text report files. Essentially, the report files get diffed with no comprehension of the content. This is useful in SWMM because the report files contain output not available from reading the binary file. This could also be useful for EPANET, for evaluating differences in engine convergence or other status messages. The downside is that diffing the report file makes for a very strict regression test. 

Unfortunately, I have not had a chance to dig into the test results and determine why they are failing. But that is next on my list ...

**Comment by samhatchett** [comment]
Cool, thanks. My only other thought would be to put all the benchmarks on S3 or similar so they don’t contribute bloat to the repo. You have any opinions on hat?

**Comment by michaeltryby** [comment]
@samhatchett storing benchmarks on S3 sounds useful. I am not opposed to doing that, but I don't have any idea how to do it either :smile:

**Comment by eladsal** [comment]
S3 or similar is good idea. I can provide the hosting, something like:
http://epant-test.s3.amazonaws.com/2PRVs.out

**Comment by michaeltryby** [comment]
@eladsal OWA already has an OWS account. @bemcdonnell set it up. I just don't know how to use it.

**Comment by eladsal** [comment]
Even better! He should probably give you permissions and then use some explorer like tool. There are simple, explorer like, tools for managing the files. I use a commercial product but there is a freeware version too (can send you a link if you want). Maybe there are open source tools too.

**Comment by samhatchett** [comment]
I wil refer you to issue #159 for some light discussion on this topic

**Comment by michaeltryby** [comment]
Closing this pull request. See Issue #159 for discussion.

**Pull request closed without merging**
