### PR TITLE
rethinking the python wrapper

### PR DESCRIPTION
**Pull request by samhatchett**
Hi folks. This PR is aimed at simplifying the interaction with external wrappers. The changes here simply unwind the conditional compilation steps that were called by wrapper generators, removes the associated source code, and suggests renaming of certain parameter declarations to make them a bit more accommodating for automatic wrapping by SWIG.

The main point of this is to remove unnecessary complexity from the core hydraulic library, to keep it as simple as possible, and maintain an uncluttered codebase - which is good for us all.

There may end up being other code that can be stripped out now - I'm just not sure. The new suggested python binding is a SWIG / scikit-build concoction, and can be found here: 
https://github.com/OpenWaterAnalytics/epanet-python/tree/dev/owa-epanet

... and the associated package can be installed simply: `pip install owa-epanet` (pending windows support)

I'm certainly open to philosophical or technical discussion about this PR, by the way.

For what it's worth, my longer strategy is to try to eventually work-in the mods that CitiLogics has made over the years (now carried on by Xylem) to enable real-time simulations via the toolkit so that we can use this community version of EPANET directly - including the great additions made by so many.

Thanks for consideration!

### CODE REVIEW

**Comment by samhatchett** [comment]
importantly (as evidenced by the above iteration on test-passing), the `EN_deleteproject` function signature has changed. It is not necessary to pass a pointer by reference (so a double pointer to the project struct) for the free-ing operations to commence. Also, changing this function better supports auto-wrapping. It may be possible to accomplish the same thing using the old function declaration, but I'll just kindly ask if this change makes anyone's lives truly difficult.

**Comment by LRossman** [comment]
Question: If the option to build the project with `epanet_py.c` has been removed from the `CMakeLists.txt` file then can `epanet_py.c` and `epanet_py.h` be removed from the project?

**Comment by LRossman** [comment]
@samhatchett I have a commit ready to address issue #513 and it would make life much easier if this PR were merged first. Thanks.

**Comment by pshassett** [comment]
@samhatchett - Do you have an idea of what the time frame is for windows support?

**Comment by samhatchett** [comment]
@LRossman - sure, lazy consensus can rule here, if there are no other comments.

@pshassett - no idea as I'm not a windows user. My plan is for someone in that world to provide some guidance or a PR. If you are in that world, please feel free to take a look!

**Comment by pshassett** [comment]
@samhatchett - Ok, good to know.  Maybe I can look into that soon.  
In the meantime this PR deprecates the [epanet_python](https://github.com/OpenWaterAnalytics/epanet-python/tree/dev/epanet_python) build, which does already support windows.

**Comment by samhatchett** [comment]
@pshassett yep - maybe that wasn't exceptionally clear from the first post ☝️ , but that deprecation is in effect what this does. I tried in the description to illuminate that a bit as well as the motivation behind it. Do you have any opinions about this?

**Comment by pshassett** [comment]
@samhatchett I see. My main concern is that now there is no python wrapper that is supportive of windows.  This is not currently an issue of high urgency however should be resolved soon at [epanet-python](https://github.com/OpenWaterAnalytics/epanet-python) in one way or another.

**Comment by LRossman** [comment]
@samhatchett the new `EN_deleteproject` signature fails to set the original project pointer to` NULL` after its memory has been freed. It's the copy of the pointer passed in by value that gets set to `NULL`, not the original project pointer created with` EN_createproject` (I just confirmed this with a small test example.) We should either revert back to passing in a double pointer or simply remove the `NULL `assignment line from the function (in which case it would be up to the client to make sure they don't try to re-use the original project pointer again without setting it to `NULL`).

**Comment by samhatchett** [comment]
thanks for the feedback - yes, I notice that the toolkit can no longer nullify the double pointer. I've seen pretty commonly in C APIs that after destroying/closing/etc some kind of handle, it's the client's responsibility to know it's dirty and not use the handle again.

That said, I'm open to either approach. Anyone have a strong preference for API usage?

**Comment by LRossman** [comment]
Although I think the original `EN_deleteproject `which used the double pointer to the project was a safer way to handle the free'd pointer, I'm ok with keeping the new version of the function. I can remove the `p = NULL;` line from it (as it serves no purpose) in my forthcoming PR.

**Comment by samhatchett** [comment]
works for me - thanks @LRossman 

also, as a bit of background, I was refreshing my memory on some of the original thoughts around the project pointer. I took great inspiration from the SQLite library - here is a snippet demonstrating creation/freeing in that api:

```
sqlite3 *db;
int rc;
rc = sqlite3_open(f_name, &db);  // reference to pointer to sqlite3 struct
sqlite3_close(db); // just a pointer to sqlite3 struct
db = NULL; // cleanup; db is dirty
```

**Pull request merged**
