### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by LRossman**
1. Added a standard header to each code module and removed obsolete comments.
2. Re-named several of the sub-structs in the project struct and re-arranged some of their contents.
3. Re-named `_defaultModel` to `_defaultProject`.
4. Removed the need to call `EN_createproject` and `EN_deleteproject` when working with the default project.
5. Made X & Y coords. part of `Snode `properties instead of a separate struct.
6. Moved the non-API functions in epanet.c into a new module named _project.c_.
7. Re-factored the quality module so that it uses the same nodal adjacency lists as the hydraulics solver.
8. Re-factored the sparse matrix module (_smatrix.c_) to be more memory efficient.
9. Restricted line lengths to < 90 columns.
10. Grouped the placement of functions in _EPANET2.H_ and _EPANET.C_ by category.

### CODE REVIEW

**Comment by michaeltryby** [comment]
Unit tests are failing. They need to be updated with the changes made to the API.

**Comment by LRossman** [comment]
Yes - no more ProjectHandle. I'll fix it and re-submit.

**Comment by michaeltryby** [comment]
Do you know that you can commit the changes to `lrossman-dev` and they will automatically be added to the PR?

**Comment by michaeltryby** [comment]
I suspect `test_setid` is failing. See Issue #339

**Comment by LRossman** [comment]
`test_net_builder` and `test_toolkit` both pass and both call `EN_saveinpfile`. Also, my local test of `test_setid` passes (I replace the `BOOST_REQUIRE` calls with calls to `cout`  -- see the code for `test_addrule`). Is there any way to tell at what line the CI test is failing? If we put debug print statements in the unit test will the CI run echo these (like it does for the build process)?

**Comment by michaeltryby** [comment]
The bug is intermittent. I suspect if you run `test_setid` locally a bunch of times you will eventually see the failure.

**Comment by LRossman** [comment]
Hold on - I spoke too soon. My local test does show a failure in picking up a test of an illegal id name. I will check further and hopefully get `test_setid` to work.

**Comment by michaeltryby** [comment]
If you build the test in Debug configuration you can get more diagnostic information about it.

**Comment by LRossman** [comment]
The only thing in the hydraulics solver that was changed was the way that parallel links are detected when the nodal adjacency lists are built for use in the sparse matrix routines. I did this so that the same lists could be used in the water quality solver as well (instead of creating a separate, duplicate set of lists just for water quality).

It turns out that the EXNET network has 98 parallel links. So my guess is that the revised parallel link routine is causing a slightly different node re-ordering which, as we've seen before, can lead to small differences in the computed results (we're talking really small in this particular case).

To ease everyone's mind I will restore the previous parallel link detection code, but still allow the re-use of the adjacency lists for water quality. I hope no one will merge with `dev` in the meantime since the effort to manually resolve diffs with this current commit with all of its cleaned up code could be enormous.

**Comment by samhatchett** [comment]
A side note here: I would encourage small merges as a normal course of practice. The `dev` branch is meant to be in flux, so small incremental (even breaking?) merges would be preferred to huge (read: conflict-prone) merges.

**Comment by LRossman** [comment]
Everything checks out OK now. I encourage review of the standardized header I placed at the top of each module and the way that the contents of `TYPES.H` were re-organized.

**Comment by michaeltryby** [comment]
Close Issue #342 #343 #345 #346

**Comment by samhatchett** [comment]
@michaeltryby from my comment above, what I was trying to say had more to do with merge frequency than with what branch it happens on.

**Comment by eladsal** [comment]
@michaeltryby again, merging such a large contribution within one day does not allow real review :(

**Comment by michaeltryby** [comment]
@LRossman Thanks for your PR. We really appreciate it! :smile:

**Comment by michaeltryby** [comment]
> what I was trying to say had more to do with merge frequency than with what branch it happens on.

@samhatchett yeah, I understand. I would have liked to have seen this one broken down into 4 or 5 individual PRs each addressing a specific aspect of the cleanup. 

Pairing an Issue with a PR creates a scope for the code changes and makes it easier for other developers to understand. Breaking blocks of changes down into smaller more frequent commits is also helpful. Especially, when using git history to try and identify bugs.

**Pull request merged**
