### PR TITLE
Issue 271 (add function ENgetheadlossformula)

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by michaeltryby** [comment]
This looks fine, but adding a function to retrieve each individual parameter has me concerned. This will lead to a cluttered API that will be difficult to use. We should be thinking how we can get more functionality out of each API call we create. Grouping parameters together and returning larger chunks of data to the user. We have been experimenting with this in the swmm API and the output APIs and it has been working out pretty well.

**Comment by Mariosmsk** [comment]
For the section [OPTIONS] we have the functions ENgetoption, and ENgetflowunits if I not mistaken. So it's better to include this function in ENgetoption?

**Comment by michaeltryby** [comment]
Yes, including this in ENgetoption() is preferred to creating yet another API call.

**Comment by Mariosmsk** [comment]
@eladsal, now? Thanks!

**Comment by eladsal** [comment]
@Mariosmsk have you seen my [earlier comment](https://github.com/OpenWaterAnalytics/EPANET/pull/272#issuecomment-418710228)?

**Comment by Mariosmsk** [comment]
I have added some parameters from adjustdata. I'm not sure if it's okay.

**Comment by LRossman** [comment]
@Mariosmsk when a user changes the head loss equation then all of the existing pipe roughness coefficients (Kc) become meaningless (i.e., a Hazen-Williams C-factor is much different than a Darcy-Weisbach roughness height). So modifying the reaction rate coefficients at the time that the head loss equation changes, based on the old Kc values, is problematic.

 Whenever a change is made to the head loss equation a corresponding change needs to be made to all of the model's Kc values. One way (maybe not the best way) to do this is to define a set of default values for each equation (KC_HW, KC_DW, KC_CM) and set all Kc values to one of these when an equation change is made.

**Comment by samhatchett** [comment]
default values are hard... I will just point out that "friendly" model-user-facing features like, for instance, stupid-proofing the act of changing headloss formulation, may well be considered outside the responsibility of the engine API. Access to the data model and its important features (in my view) should be a separate concern from ensuring that the user knows what they are doing. Specifically, auto-changing roughness coefficients looks more like a application-level feature than an engine feature.

**Comment by Mariosmsk** [comment]
I agree with @samhatchett. I think is better to set headloss formula and the user change parameters coeff. as he wants.

**Comment by Mariosmsk** [comment]
So, when the user changes the headloss formula a warning could be displayed to inform the user that the current pipe roughness coefficients are meaningless if the formula is changed and further actions are required. e.g.:

#define WARN7 "WARNING: Pipe roughness coefficients may become invalid when headloss formula is changed. Further actions may be required."

**Comment by michaeltryby** [comment]
Ok, so you change the headloss formula, the pipe roughness coefficients become invalid, and the internal state of the engine is essentially corrupt (it can't produce meaningful results). The user gets a warning and then what? How is the user going to correct this situation? 

They would need to iterate over all the pipes in the network and recalculate the roughness coefficients for each of them. Would any other internal state of the model need to be updated? 

Does the toolkit provide the necessary functionality to bring the model back into a valid state where it can produce meaningful results?

**Comment by Mariosmsk** [comment]
Added get option for headloss formula here #293. Maybe leave open this issue for the set of headloss formula.

**Comment by eladsal** [comment]
Closed by #293

**Pull request closed without merging**
