### PR TITLE
Fix problems with setting tank parameters (issue #464 )

### PR DESCRIPTION
**Pull request by LRossman**

### CODE REVIEW

**Comment by LRossman** [comment]
Issue #29 has been resolved. I commented earlier on #35 which can still be problematic in some (rare) cases. It falls in the same category as eliminating water level instabilities in connected tanks (which if you recall we tried to fix but dropped due to numerical difficulties). IMHO, finding an iron clad fix for both of these issues is best left for a future enhancement,

**Comment by michaeltryby** [comment]
Ok that means that we have our release candidate in the can.

**Comment by LRossman** [comment]
@michaeltryby no, not just yet please. Your excellent work in using a generic list to manage demand categories got me thinking about how we can make it even better (mainly the _demand.c_ part of it). I'd like a few days to pursue my ideas. Thanks in advance for your patience.

**Comment by michaeltryby** [comment]
@LRossman that's fine. It will give folks a few days to chime in on release candidate status.

**Pull request merged**
