### PR TITLE
Feature Update - more rigorous hydraulic convergence criteria (#161)

### PR DESCRIPTION
**Pull request by LRossman**
New analysis options named `HEADERROR `and `FLOWCHANGE `were added, where head loss error must be less than `HEADERROR `and flow change must be less than `FLOWCHANGE `for the hydraulic solver to converge. Default values for these options are 0 meaning they are ignored.  The existing relative flow change criterion `ACCURACY `still applies.

Also the HYDRAUL.C file was broken into 3 separate files to improve code readability.

### CODE REVIEW

**Comment by michaeltryby** [comment]
@LRossman thanks for the PR. Unfortunately, it breaks the build on Appveyor and Travis. Please have a look at the build logs.

**Comment by michaeltryby** [comment]
@LRossman on PR #177 we had all tests passing on Appveyor for both the VS2010 and VS2017 32 bit builds. Now both are failing. Since the input files haven't been updated, the new convergence criteria shouldn't be active. Hence the tests should be in the green, so I guess I'm confused. 

Also would it make sense to add some test cases with the new convergence criteria active to insure that the changes are working properly?

**Comment by LRossman** [comment]
I tested a subset of your networks (nw_model, wolf-3, and sampletown) by using a diff tool on the report files generated by the latest build and 2.0.12. All flows matched to 2 decimal places. Then I added net1 to the mix, since I see that it failed your latest test. Again, all flows matched to 4 decimal places, but there was a difference in the relative error values reported for trials at times where a pump changed status. I'm not sure if this is included in your diff testing, but it needs to be addressed so a new PR will be forthcoming.

I don't know what your test is comparing - is it the numbers in the binary results file or in the plain text report file. If it's the latter, then the new code adds additional lines to a full status report listing the maximum head error and flow change at each trial, even when those criteria are not used.

It also seems that you changed epanet_output.c since the build process generates two warning messages that didn't appear in earlier builds. Could that be a factor?

**Comment by michaeltryby** [comment]
@LRossman I haven't made any changes to epanet-output, but even so, on Appveyor the epanet-output library gets installed from a python wheel built a priori. So there is no way for it to be different.  

`nrtest-epanet` compares every value written to the binary files and it diffs the output files. It is configured to fail fast to flag differences when they occur. You can see the code [here](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/tools/nrtest-epanet/nrtest_epanet/__init__.py). It iterates over two binary file simultaneously and pulls the results out, in the order they were written and compares them. For report files, it ignores a predefined header and footer and iterates over two text file and compares them line by line. That's all it does. It just automates the types of checks you perform. 

Since the new convergence criteria in this PR are not being activated by any of the existing regression tests, theoretically, the results should be exactly the same as before. But they are not. So is it possible that a bug or unintended change has crept in? Catching bugs is what this is all about!

**Comment by eladsal** [comment]
I see that `epanet2.h` was moved from the `include` folder to `src` - I don't have a strong position on this but was that intentional? Also `main.c` is now in `src`.

**Comment by samhatchett** [comment]
I'm not in favor of moving files around as @eladsal has noted. `CLI/main.c` and `include/epanet2.h` are good locations.

**Comment by michaeltryby** [comment]
Tests still failing.

**Comment by LRossman** [comment]
I restored the moved files (which were moved by accident) to their original locations.

I see that my latest commit has also failed the AppVeyor checks. This is very frustrating in that my own tests comparing results from the plain text report files show either complete agreement or very minor differences. See the files with results from EPANET 2.00.12 [2.00.12.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2115804/2.00.12.zip) and for my latest commit [2.2-dev2.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2115810/2.2-dev2.zip) for a subset of the regtest files, some of which failed.

At this point I am at a loss as to how to proceed.

**Comment by michaeltryby** [comment]
I run the reg tests locally. You could try doing that.

**Comment by LRossman** [comment]
How does one run the reg tests locally?  I find them not very useful for debugging since they don't tell you which was the offending network element, variable, and time period.

**Comment by michaeltryby** [comment]
> How does one run the reg tests locally?

A link to some instructions that you may or may not find helpful can be found [here](https://github.com/michaeltryby/EPANET/blob/dev/.github/BuildAndTest.md).

**Comment by LRossman** [comment]
Thanks @michaeltryby . Two questions about the nrtest commands:

1. Where is the "regression test location"?
2. Is the location of the Python scripts `\tools\nrtest_epanet` ?

**Comment by michaeltryby** [comment]
@LRossman The before-test.cmd script will stage the reg testing files anywhere you tell it to. I usually create a “nrtestsuite” directory right in the EPANET project tree.  

On Windows you need to provide the path to the Python ‘Scripts’ folder to call the nrtest-execute and nrtest-compare commands. You can find it where Python gets installed.

**Comment by michaeltryby** [comment]
The Appveyor build worker runs Windows. While the Travis build worker runs Ubuntu Linux. We have not as of yet established a benchmark on Linux. 

On the report file comparison issue we have several options 1) shut it off, 2) update the benchmark, or 3) write a better nrtest plugin for comparing report files.

**Comment by LRossman** [comment]
The test failures due to numerical differences with the benchmark occurred only for models using the Darcy-Weisbach head loss formula. The reason was simple -- my commit also included a correction to how EPANET computes the head loss derivative as noted by Simpson and Elhay (J. Hyd. Engrg, 137(6), 2011). After removing this correction the failed files all passed (according to my own diff tests). I will post the need to correct the D-W calculation as a new issue to be addressed in the future so we can move forward with this one.

**Comment by eladsal** [comment]
@LRossman, my commit (f86df22) does not change the reporting but only limits the addition of the new parameters to the INP file if they are not specified by the user (so the default values will be used).

**Comment by michaeltryby** [comment]
@eladsal maybe instead of tacking your commit onto @LRossman 's PR you could open an issue and describe the problem so we can have a forum and opportunity to discuss the merits of your proposal.

**Comment by eladsal** [comment]
@michaeltryby well, this could go either way. Here we are discussing **this** PR. On the other hand, I should have probably suggested this instead of committing but I felt this was a minor thing. Thanks.

**Comment by LRossman** [comment]
I read @eladsal's commit too quickly and assumed it was trying to address the reg test failures when comparing status report files. Now that I've re-read it after he explained it I'm OK with it. @michaeltryby I don't see the need to raise a new issue on it.

**Comment by LRossman** [comment]
The Appveyor fails were all due to added lines of output in the Status Report. Numerical results in the binary output files were all identical. Therefore please merge this commit so we can move on to resolving additional issues.

**Comment by michaeltryby** [comment]
@LRossman that's great! Did you want to add some test cases to the reg testing suite that target the new convergence criteria? That way we can be sure that the functionality you added is working properly. 

I will work on updating the benchmark to reflect the changes in the report file summary. I will also start an SOP for benchmark updates. I will make a commit or two to get your PR working with the new benchmark and then we can go ahead and commit it.

**Comment by michaeltryby** [comment]
@LRossman If you are going to add tests I will need those before I can update anything. Since I need to add them to the `epanet-example-networks` repo and create a tag. Thanks!

**Comment by LRossman** [comment]
I will prepare a couple of test cases that show that the new convergence criteria are functioning properly (I've already done this informally on my local machine).

Also, regarding the update to the benchmark. Once you're convinced that a commit to the dev branch is legit, wouldn't it be easier to just use that as the new benchmark executable for future commits instead of always using EPANET 2.0.012?

**Comment by michaeltryby** [comment]
@LRossman great question.  EPANET 2.0.12 is the current benchmark simply because it was the last "official" release and we needed a place to start. When new functionality and new reg tests get added, obviously the benchmark app needs to change. Otherwise the new test cases would always fail. 

So benchmarks need to move forward and keep in step with development. For example, we have already shifted the benchmark from Visual Studio 6 to Visual Studio 10. However, benchmarks also need to be fixed to releases. We need to reflect this in the SOP somehow. Maybe through the tag numbering scheme or something. Thoughts?

**Comment by LRossman** [comment]
So I'm not understanding why benchmarks have to be fixed to releases. It seems they should simply roll-over from one official commit to the next. I mean if the last "master" release for this project was 2.1 then it doesn't need a benchmark anymore. It should have been the benchmark for the first version of 2.2 (which I guess is what is called the dev branch). The benchmark should stay the same until a PR breaks it and, like we did with this PR, reviewers are convinced by the contributor that the changes he/she made are valid. So when the new commit gets approved its executable becomes the new benchmark. If the branch has to be reverted to a prior state (can you do that?) then the executable from that state becomes the current benchmark.

Another part of an SOP to consider is a requirement that contributors submit a unit test that exercises the changes they made (with maybe exceptions for obvious bug fixes) to demonstrate that they work as intended. I'm not necessarily talking about unit test code modules but rather EPANET input files along with scenario narratives that illustrate how the change/update worked correctly.

**Comment by michaeltryby** [comment]
@LRossman I agree for the most part, however, I feel that only maintaining a rolling benchmark could contribute to solution drift over time. Thus I prefer a scheme where we anchor benchmarks to releases and maintain a rolling benchmark that tracks development.

**Comment by michaeltryby** [comment]
@eladsal the benchmarks are housed as tagged releases in the `epanet-example-networks` repo. The test scripts are setup with the URLs and tags of the benchmark files. So for a tagged release we would build an executable, generate the benchmarks, tag a benchmark release, and update the test scripts with the corresponding benchmark tags. Then we would tag the release version of EPANET and the tests would be in the green. Make sense?

**Comment by eladsal** [comment]
@michaeltryby  I understand, so the benchmark `out` and `rpt` files are produced offline and not by the testing scripts, right?

**Comment by michaeltryby** [comment]
@eladsal Yes that is correct. I setup the reg test environment locally. Then run nrtest-execute to generate the benchmark artifacts and a manifest.json file. Then zip it and add it to a release in the `epanet-example-networks` repo. 

We could generate the benchmark artifacts directly on the CI server, but I think grabbing them from a release how we currently do is working out pretty well.

**Comment by michaeltryby** [comment]
Just to be clear, running locally and using `nrtest-execute` and `nrtest-compare` one can compare any two version of EPANET that you want as long as the binary file formats are the same.

**Comment by michaeltryby** [comment]
@LRossman I need those test cases to more forward on my end.

**Comment by LRossman** [comment]
[RegTests.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2133923/RegTests.zip) contains two variations on the existing exnet-3.inp test case (where the `ACCURACY `level was only 0.1). The first applies a `HEADERROR `option of 0.1 m and the second a `FLOWCHANGE `option of 0.1 LPS.

**Comment by michaeltryby** [comment]
@LRossman your tests have been added and the benchmark has been updated. Reg tests on Appveyor are in the green. Reg tests on Travis are operational but failing. 

This PR is good for merge.

**Pull request merged**
