### PR TITLE
Added the link to the step-by-step tutorial

### PR DESCRIPTION
**Pull request by eldemet**
I've added this link here, but perhaps it could move to a different location to do this as well (the wiki?).

### CODE REVIEW

**Comment by eladsal** [comment]
Can you embed the Slideshare pres in the Wiki?

**Comment by eldemet** [comment]
I cant embed slideshare, as iframe is not supported in github, if I'm not mistaken.

Other options: 
1. Extract all slides from the Powerpoint as images and put everything in a single Wiki page.
2. Put the first slide as image with hyperlink to the slideshare website.

**Comment by eladsal** [comment]
No problem to start with a link to Slideshare

**Comment by eldemet** [comment]
Added this Wiki page: https://github.com/OpenWaterAnalytics/EPANET/wiki/Step-by-step-guide-on-how-to-contribute-to-EPANET-using-GitHub

**Pull request merged**
