### PR TITLE
Minor updates to ENOutputWrapper.py; Adding OutDiff.py

### PR DESCRIPTION
**Pull request by bemcdonnell**
#16 @samhatchett, I pulled together a very simple function to compare the output files.  This is command line ready and returns a True/False for pass/fail. @michaeltryby suggested that I keep this more simple instead of taking the min(-log (abs (v1-v2)) as @jamesuber suggested.  Once you get this into the testing process, we can make changes as needed.

The function loops through the attributes for all nodes at time t (currently the fastest way to parse the output file using the @michaeltryby's API).  The absolute difference of each value is compared against the allowable threshold.  If value passes the allowable threshold, the function wastes no time to return False.  

Please feel free to make any changes to this! I will be out for a few days and I wanted to give you all a starting point.

### CODE REVIEW

**Comment by michaeltryby** [comment]
The idea here is to create something quickly to cover the Travis CI testing use case - compare two binary files as efficiently as possible and return True or False. This script is not meant to provide detailed information about the differences present or their significance. Thus, the min(-log(abs(v1-v2))) was omitted for the sake of efficiency. 

Obviously, it would be straight forward to expand the script to provide more detailed information if this is where we want to cover the more detailed testing use case.

**Comment by samhatchett** [comment]
Quickly getting to a test makes sense. I like to call this sort of thing "version zero" 👍🏻

**Comment by jamesuber** [comment]
Is true and false supposed to be meaningful at this point, or is this intended to only test a tool chain?

**Comment by michaeltryby** [comment]
Yes, true or false is meaningful. And yes this is needed to get the CI test tool chain working.

**Pull request merged**
