### PR TITLE
Add support to build for default and python library targets

### LINKED ISSUE #376: Eliminating the need to use WITH_GENX and epanet2_export.h in client code
I found a way to modify the cmake scripts and the EPANET2 header files so that client C/C++ apps can use `epanet2.dll` without having to define `WITH_GENX` or include `epanet2_export.h` in their builds. (Note: this does not apply to VB/VBA/Delphi apps which still need a version of the DLL built with a `def ` file.) The required changes are:
1. Remove all lines that contain `WITH_GENX` in all of the cmake scripts and in the pre-processor statements in `epanet2.h` and `epanet2_2.h`.
2. Re-write the pre-processer statements that define `DLLEXPORT` in `epanet2.h` and `epanet2_2.h` as follows:
```
#ifndef DLLEXPORT
  #ifdef WINDOWS
    #ifdef epanet2_EXPORTS
      #define DLLEXPORT __declspec(dllexport) __stdcall
    #else
      #define DLLEXPORT __declspec(dllimport) __stdcall
    #endif
  #elif defined(CYGWIN)
    #define DLLEXPORT __stdcall
  #else
    #define DLLEXPORT
  #endif
#endif
```
This works because the Visual Studio compiler automatically adds `/D epanet2_EXPORTS` to its command line.

After making these changes I rebuilt the project using cmake with Visual Studio 2017 and the resulting command line executable `runepanet.exe` worked as before. I then locally rebuilt one of the test projects (`netbuildertest2.cpp`) without using `WITH_GENX` or `epanet2_export.h`. The resulting executable ran successfully. Finally, I did a test commit and PR of these changes to the `dev` branch and it passed the CI tests.

Does anyone have an objection to merging these changes into `dev`?

### LINKED ISSUE #382: cmake add def file support
See Issue #154 

This can be accomplished as a build option or as a new build target for dll exposing the legacy API. Rather than by rolling back support for import libraries as proposed in Issue #376.

### PR DESCRIPTION
**Pull request by michaeltryby**
Close #376
Close #382 

This PR creates a default `epanet2` library target that exposes the 2.0 and 2.2 Toolkit APIs. And a custom `epanet_py` library target specifically for the python wrapper build. This is accomplished using API versioning to exclude different versions of the API from the respective targets and using the cmake `option` command. A small change was also made in `epanet2_2.h` so that `DLLEXPORT` is properly defined when building the default and `epanet_py` targets.

### CODE REVIEW

**Comment by michaeltryby** [comment]
This PR also incorporates @LRossman 's ideas from Issue #376 into the default `epanet2` library build.

**Comment by michaeltryby** [comment]
@LRossman Thanks for your review. I would prefer that the files stay put for now. If it turns out developers are confused by their current locations I'm open to making adjustments as needed. Sound good?

**Comment by eladsal** [comment]
It seems that this PR broke the `wini_build` script.
I don't understand why but when compiling I'm getting the following error for all the functions:
`epanet.c(47) : error C2491: 'EN_createproject' : definition of dllimport function not allowed`
I think it is related to changes to `epanet2_2.h` and\or `epanet2.h`

**Comment by LRossman** [comment]
It might be related to the` /Depanet2_EXPORTS` directive that automatically gets generated with the `cmake` build. Try adding it the `cl` command in your build script.

**Comment by eladsal** [comment]
@LRossman that did the trick, thanks.

**Pull request merged**
