### PR TITLE
Syntax for the epanet executable

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by michaeltryby** [comment]
Closes #228

**Comment by michaeltryby** [comment]
@Mariosmsk your last commit to this PR breaks the build.

**Comment by eladsal** [comment]
@Mariosmsk It is probably the cmake build script since you included `text.h` in `main.c`. The `win_build` script builds it correctly.

**Comment by Mariosmsk** [comment]
@eladsal, yes with `win_build` its ok.

**Comment by Mariosmsk** [comment]
c:\projects\epanet\run\main.c(3): fatal error C1083: Cannot open include file: 'text.h': No such file or directory [C:\projects\epanet\buildprod\runepanet.vcxproj]

**Comment by michaeltryby** [comment]
The thought behind duplicating the formatted strings in the `main.c` was so it could be compiled solely with the `epanet2.h` header. The `text.h` header is internal to the library and not part of the exported API or included headers needed for using it. This is standard practice when linking against a library. 

So I'm not in favor of these changes you are making.

**Comment by michaeltryby** [comment]
If these format strings are only used in `main.c` and you want to eliminate duplication. Remove them from `text.h` instead.

**Comment by eladsal** [comment]
Some of them are needed in both. I would keep the duplication.

**Comment by michaeltryby** [comment]
Actually FMT01, FMT03, FMT09, FMT10, FMT11 are only referenced from `main.c`

**Comment by Mariosmsk** [comment]
Its ok now! I have make comment the lines with FMT01, FMT03, FMT09, FMT10, FMT11 in `text.h`

> Build success

**Comment by eladsal** [comment]
This is fine by me. Only thing that the commented strings in `text.h` could be deleted.

Thanks @Mariosmsk

**Pull request merged**
