### PR TITLE
Improved modeling of tank dynamics (Issue # 165)

### PR DESCRIPTION
**Pull request by LRossman**
The option to use an IMPLICIT method (instead of the traditional EXPLICIT method) for updating tank levels was added that produces more stable results. How to use it is described in the updated [v. 2.2 Release Notes](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/ReleaseNotes2_2.md). A test example can be found here: 
[Todini1.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2325465/Todini1.txt). The results for this example, illustrating more stable tank dynmaics, are shown here
 
todini1
This update will fail the reg tests for those files that request an input summary be written to EPANET's Status Report since it adds a new line to the summary that lists the method use to model tank dynamics.

### CODE REVIEW

**Comment by michaeltryby** [comment]
@LRossman also curious why not totally switch over to the implicit solution and deprecate the explicit solution.

**Comment by LRossman** [comment]
@michaeltryby I'm perfectly fine with replacing the explicit method with the implicit one if people won't mind seeing different (but more realistic) results. In most cases where tanks are not hydraulically connected to one another the difference will be negligible. When they are hydraulically connected the results will be better. If there is consensus on just going with the implicit method then I will cancel this PR (how do I do that?) and submit a new commit that replaces the explicit method with the implicit one instead of creating two options.

**Comment by michaeltryby** [comment]
@LRossman I am fine switching over to the implicit method. What do other people think?

**Comment by jamesuber** [comment]
I am all for it. Out with the old!

Jim Uber • 513-368-6303 • www.citilogics.com

**Comment by michaeltryby** [comment]
You can close a pull request without merging it. Then you can start a new one. Be sure to update your fork first. Here is a link that explains how: 

https://help.github.com/articles/syncing-a-fork/

**Comment by LRossman** [comment]
Closing this PR to re-work tank dynamics.

**Pull request closed without merging**
