### PR TITLE
update example code Hydraulic & Quality analysis steps

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by LRossman** [comment]
@Mariosmsk I believe that `ENnextH` has to be called before `ENnextQ`, not after.

**Comment by Mariosmsk** [comment]
Yes. Also, I think it's good to add something like the following code before analysis:  
```
tstep = 3600
ENsettimeparam( EN_HYDSTEP, tstep)
ENsettimeparam( EN_QUALSTEP, tstep)
```

**Comment by LRossman** [comment]
Actually one doesn't need to set `EN_HYDSTEP` to 3600 sec since that is the default for a new project. Also, using that same value for `EN_QUALSTEP` is not recommended - water quality needs to be calculated on a much smaller time step, closer to the smallest time of travel through a pipe, to produce accurate results. Its default value is 360 sec.

**Comment by Mariosmsk** [comment]
I agree with you. This PR I think it's ok for merge. Thanks

**Pull request merged**
