### PR TITLE
Fixup local testing

### PR DESCRIPTION
**Pull request by samhatchett**
the real purpose here is to remove duplication among the `.sh/.cmd` testing scripts, and to provide an easier way to run regression tests locally. 

so we've got marginally better functionality, no additional dependencies, and more lines removed than added. cool, huh?

TODO items: 

- fix Appveyer config
- fix benchmark binary files for gcc/linux
- or adjust tolerances?

### CODE REVIEW

**Comment by michaeltryby** [comment]
@samhatchett Great job!

Trusty-backports has a [swig3.0](https://packages.ubuntu.com/trusty-backports/swig3.0) package. If we can figure out the magical incantation to install it we can avoid building it.

**Comment by samhatchett** [comment]
Yep building SWIG is a pain. We could also look into using a preconfigured Docker container to run the builds. That way Travis would only have to download one image and then start building our code.

**Comment by michaeltryby** [comment]
@samhatchett Thinking about it some. The CI use case and the local testing use case are different. With CI starting from a clean working image I want to build the SUT, stage the testing environment, and run the tests. When running locally I stage the testing and then build and run tests on the SUT many times. 

Since, I do not want to stage testing every time I run the tests those two steps in the process need to be separated out when running locally. Make sense?

**Comment by samhatchett** [comment]
yep, makes sense. it's a bummer to download the resources every time the script is run. Thanks for the feedback!

**Comment by michaeltryby** [comment]
@samhatchett were you planning on fixing Appveyor as part of this PR?

**Comment by samhatchett** [comment]
@michaeltryby - yes, I guess no PR would be complete without it. I will plan to fix Appveyer, and split the testing script into staging/testing portions. Thanks again for the feedback!

**Comment by samhatchett** [comment]
please don't think I forgot about this, but please don't anybody plan to merge this, since it's too far behind. I will refactor and resubmit, but keep this open here for now as a reminder. 

I still think it's a good idea to remove duplication between windows/linux scripting files. standardizing on x-plat python seems a good call, right?

**Comment by michaeltryby** [comment]
@samhatchett yeah I agree the current approach is cluttered and needs to be simplified.

**Comment by michaeltryby** [comment]
@samhatchett Going to close this PR due to inactivity. Your contributions are always welcome and you may reopen it again in the future when you have time and inclination to finish it.

**Pull request closed without merging**
