### PR TITLE
Format arg

### PR DESCRIPTION
**Pull request by bradleyjeck**
Dear Maintainers,  
The change in this PR were made to pass checks required of compiled C code in R packages.  I submit it here for possible inclusion in the next release of EPANET.    

calls to sprintf() should include a format string

### CODE REVIEW

**Comment by eladsal** [comment]
This is fine by me. travis-ci is also warning about this (line 923 in dev)

**Comment by bradleyjeck** [comment]
Thanks @eladsal, the [build of the R package (line 1075)](https://travis-ci.org/bradleyjeck/epanet2toolkit) has a handful of other warnings from the a gcc based compilation.  A peek at the build of the dev branch shows the same warnings.  

Once I understand the contributing flow here, I'm happy to try and fix those to clean up both builds.

**Comment by michaeltryby** [comment]
Any objections to merging this?

**Comment by samhatchett** [comment]
let's not merge this into master. I tried to rebase, but apparently i don't know the right Git-fu moves.

**Comment by bradleyjeck** [comment]
was merged into dev as #134 so i think this PR can be deleted

**Pull request closed without merging**
