### PR TITLE
use docker image to package build dependencies

### PR DESCRIPTION
**Pull request by samhatchett**
this ended up being pretty cool! 

old travis config, building and installing everything: 4m17s
new config, using docker: 2m45

... I think there's a way to cache the docker image in Travis, which will lead to better savings.

### CODE REVIEW

**Comment by michaeltryby** [comment]
@samhatchett I am new to docker. Are you defining openwateranalytics/epanet_builder in the .travis.yml or referencing it from somewhere else?

**Comment by samhatchett** [comment]
@michaeltryby I'm referencing from elsewhere. Probably should have its own repo, but it's very simple:

```
FROM python:3

RUN apt-get update
RUN apt-get install -y libboost-test-dev libpcre3-dev bison cmake
RUN pip install pipenv
RUN wget -O swig-rel-3.0.12.tar.gz https://github.com/swig/swig/archive/rel-3.0.12.tar.gz
RUN tar -xf swig-rel-3.0.12.tar.gz
RUN cd swig-rel-3.0.12 && ./autogen.sh && ./configure && make -j 4 && make install && cd ..
RUN rm -rf swig*
WORKDIR /epanet
```

**Comment by michaeltryby** [comment]
@samhatchett so is the docker container running Ubuntu Trusty?

**Comment by samhatchett** [comment]
@michaeltryby this docker image is based on "Debian GNU/Linux 9 (stretch)" - but it runs on the kernel of the host machine, whatever that is. 

could be that Docker is not a great fit for Travis CI - we could instead use Travis' Cache system for the built SWIG dependency (or others too). It's just not great to waste time and cpu on building/installing the same things over and over.

**Comment by michaeltryby** [comment]
@samhatchett Docker looks super cool. Appveyor also supports Docker when you select the Visual Studio 2017 Build Worker Image.  My computer here at the EPA is so locked down that I am unable to do anything useful with the Windows Docker client I installed. As such, I haven't had the opportunity to learn it. Perhaps moving to Docker just to avoid building SWIG is not necessary. I am confident we can install it from trusty-backports. 

On Appveyor once the build and tests passed the cache updated and started working. Maybe Travis is setup the same way. Then we can configure it and shave some time off the build.

**Comment by michaeltryby** [comment]
@samhatchett Going to close this PR due to inactivity. Your contributions are always welcome and you may reopen it again in the future when you have time and inclination to finish it.

**Pull request closed without merging**
