### PR TITLE
edit pump power on getlinkvalue function

### PR DESCRIPTION
**Pull request by milad-ghiami**
hi 
i  think you must edit getlinkvalue  for get pump power by link[index]->km on line 2047
form this
```
 case EN_MINORLOSS:
      if (Link[index].Type != EN_PUMP) {
        v = Link[index].Km;
        v *= (SQR(Link[index].Diam) * SQR(Link[index].Diam) / 0.02517);
      } else
        v = 0
      break;
```
to this
```
 case EN_MINORLOSS:
      if (Link[index].Type != EN_PUMP) {
        v = Link[index].Km;
        v *= (SQR(Link[index].Diam) * SQR(Link[index].Diam) / 0.02517);
      } else
        v = Link[index].Km*Ucf[POWER]; /*return power*/
      break;
```

### CODE REVIEW

**Comment by milad-ghiami** [comment]
mybe to  this 
v = Link[index].Km*Ucf[POWER]

**Comment by milad-ghiami** [comment]
@eladsal its true?

**Comment by eladsal** [comment]
I'm not sure I understand the problem that this solves, can you please explain?

**Comment by milad-ghiami** [comment]
when you went to get power of pump by API function,
has not enum for get power of pump,
power of pump save in  link[[index].km while km for valve and pipe is EN_MINORLOSS 

if you went get it you call this 
 ENgetlinkvalue(  [index of pump]  ,  [EN_MINORLOSS ] , &v )  
after it v is zero

**Comment by eladsal** [comment]
OK, now I see what you mean, there is no way to get (or to set) the pumps power (and also the speed). You are right and these options are needed. However, I don't think that it is good practice to get the power setting via the `EN_MINORLOSS` enum but use something like `EN_POWER` and `EN_SPEED` (we should add them if they don't exist).

Let me suggested how to move forward on this:
1. Open an issues suggesting to add the option to get (the set function can go here or in another issue).
2. Suggest a way to do it (as you suggested using the `ENgetlinkvalue` function and using `EN_POWER`)
3. Ask for input. For example, the power setting is valid only for `EN_CONST_HP` pump type, what should be returned for other types? Zero, error...? Another thought is to check if you need unit conversion? I think it is set always in HP so no need to convert. Speed values are unitless so no need to convert.
4. I'd start with the get function since the set one would require some other considerations as other pump properties may be needed to be updated.
5. Get feedback and make the changes. Then make a new pull request.

It may seem a longer way but it is the high road :)

**Comment by milad-ghiami** [comment]
i open issue [this](https://github.com/OpenWaterAnalytics/EPANET/issues/215)

**Comment by eladsal** [comment]
Work on this has moved to #215. Thank you @milad-ghiami

**Pull request closed without merging**
