### PR TITLE
Get and set pressure units in toolkit

### LINKED ISSUE #715: Support for kPa is undocumented and not included in the toolkit API
EPANET includes support for metric networks to provide results in both meters and kPa, however, this functionality is not documented either in OWA-EPANET or any [official EPANET documentation](https://epanet22.readthedocs.io/en/latest/8_analyzing_network.html?highlight=options#setting-analysis-options) I can find.

You can find the implementation of kPa within the codebase at these locations:

**Reading PRESSURE in [OPTIONS] when reading an INP**
https://github.com/OpenWaterAnalytics/EPANET/blob/278037bab30960ad2623fb6f360e3f7900124ac2/src/input3.c#L1799-L1807

**Setting kPa when initializing units**
https://github.com/OpenWaterAnalytics/EPANET/blob/278037bab30960ad2623fb6f360e3f7900124ac2/src/input1.c#L424-L425

**Setting pressure conversion factor**
https://github.com/OpenWaterAnalytics/EPANET/blob/278037bab30960ad2623fb6f360e3f7900124ac2/src/input1.c#L443-L444

**Including PRESSURE in [OPTIONS] when calling EN_saveinpfile**
https://github.com/OpenWaterAnalytics/EPANET/blob/8d8ccafad6d9864063362de5a79377dfc52f987a/src/inpfile.c#L638

This leads me to two questions:
1.	Is support for kPa intended, even though it is undocumented?
2.	Should we include APIs to allow toolkit users to access and set this option?

If the answers are yes to the above I propose that:
1.	Documentation is updated to include this option
2.	Functions are added to the toolkit to support setting and getting pressure units

My initial assumption is this will be two functions, `EN_setpressureunits` & `EN_getpressureunits`, and also exporting the enum `PressureUnitsType`

### PR DESCRIPTION
**Pull request by lbutler**
Implemented using `EN_PRESS_UNITS` as an option to `EN_getoption` and `EN_setoption`.

`EN_PressUnits` enum uses `EN_PSI`,`EN_KPA` & `EN_METERS` which matches internal options but differs from epanet-output which uses `ENR_MTR`.

I added testing to cover all cases I could think of, but it may be more than what is required, so I can reduce it if you prefer.

Fixes #715

### CODE REVIEW

**Comment by LRossman** [comment]
If a user switches pressure units, say from meters to kPa, then shouldn't all network parameter data that were entered in meters be converted to kPa as well. These parameters would include pressure bounds used in PDA models, pressure limits assigned to PRVs and PSVs, and any pressure limits used in simple and rule-based controls.

**Comment by lbutler** [comment]
Good catch @LRossman, if someone else doesn't do it I can confirm later in the week.

I assume since most other conversions are handled, we would not need to create a new API for conversions. Instead, create an internal function to deal with this case when `EN_setflowunits` was called or the pressure units were changed between kPa/meters.

If we confirm its needed and that's the approach we're going with I can also update the PR later this week too.

**Comment by LRossman** [comment]
Correct, no new API conversion feature is needed (I'm going to close issue #720 shortly). Just a new function in rules.c to handle the units conversion for condition clause variables.

**Comment by lbutler** [comment]
I made some changes to the code so that when users change the units of flow or pressure, the units in the rules will also update. To do this, I created a function that converts the units in the rules when the user changes the units using the toolkit.

Another option would be to change the way the rules work so that they use the internal units instead, but that would require a lot of changes to the code, so I decided to go with the simpler option for now.

The following changes were made in the latest commit:

- New function `updateruleunits` which is called from `EN_getflowunits()` and `EN_setoption()` with `EN_PRESS_UNITS`
- Created a new unit testing suite under `test_units.cpp` and moved all tests to this file
- Created tests to check pressure bounds

There is a bit of code added here, please provide any comments, and nothing is too pedantic. I'm happy to modify anything to match the current style/convention.

**Comment by LRossman** [comment]
@lbutler good work. I don't see any issues with your code changes so I will merge the PR.

**Pull request merged**
