### PR TITLE
Updating Appveyor to use epanet-output binary wheel

### PR DESCRIPTION
**Pull request by michaeltryby**
Addresses Issue #155 on Appveyor

### CODE REVIEW

**Comment by michaeltryby** [comment]
Tests are operational but failing.

**Comment by eladsal** [comment]
No objections.
One small comment, I think we stopped adding author names to files, all kept in the repo.

**Comment by samhatchett** [comment]
I think I'm disagreeing with the concept that the output binary parser used for the tests should come from a release. The code for the parser is in this repo, right? So changes to the parser here won't be reflected in these tests.

**Comment by michaeltryby** [comment]
@eladsal I add my name as author to the file so my work can be more easily identified. Because I am a Federal Employee my work resides in the Public Domain.

**Comment by eladsal** [comment]
Sure, no problem.

**Comment by michaeltryby** [comment]
> I think I'm disagreeing with the concept that the output binary parser used for the tests should come from a release. 

@samhatchett I agree. I am attempting to implement the organization structure you described in Issue #123. This organization separates the Python concerns from the C library concerns and introduces a circular dependency between the epanet and epanet-python repos discussed in Issue #146. It as unlikely that the binary file format is going to change substantially anytime soon. Making this circular dependency more theoretical in nature. 

I believe that satisfying the Python dependency for epanet-output using a binary wheel as the most straight forward path to proceed with the reorganization. Does this make sense?

**Comment by samhatchett** [comment]
I don't think this is what I described in #123 - although many ideas have been discussed. The fact that, as part of testing C code, all of that C stuff has to get built is actually an asset... because even given the assumedly stable nature of the binary format, the parser code in this repo may change - perhaps accidentally. Using a cached version of the binary may make CI testing go faster, but acts agains intuition about what is really being tested. I'm just not convinced this type of circular dependency is really necessary. If we must use Python testing code that depends on python wrappers, those wrappers should wrap fresh code.

**Pull request merged**
