### PR TITLE
Replace fixed-sized comment strings with dynamic strings

### PR DESCRIPTION
**Pull request by LRossman**
This commit addresses issue #422.  It also adds a new unit test named `test_comments.cpp `to test the switch to dynamic comment strings along with the new API functions `EN_getcomment` and `EN_setcomment`.

### CODE REVIEW

**Comment by michaeltryby** [comment]
@LRossman Nice PR!

**Comment by michaeltryby** [comment]
@LRossman Hey that last merge broke the build!

**Comment by LRossman** [comment]
@michaeltryby the commit passed 3 days ago. I just issued another PR of the same code and it failed the Travis CI test. Did you make changes that broke the build? How can we restore the last version of `dev` that passed?

**Comment by michaeltryby** [comment]
@LRossman I made some changes to get the unit tests to build faster. I suspect that's the problem, since the test is the part of the build that is failing. I will take a look.

**Pull request merged**
