### PR TITLE
Fix pump curves

### PR DESCRIPTION
**Pull request by AbelHeinsbroek**
Fixes issue #314 that occurs when adding multiple pumps with different pump curves.

### CODE REVIEW

**Comment by AbelHeinsbroek** [comment]
The AppVeyor test seems to be failing due to the test not being able to load the generated input file, and not due to an error in the toolkit code. Can someone with a windows development environment help me fix the test?

**Comment by LRossman** [comment]
@AbelHeinsbroek I just pushed my own fix for #317 that eliminates the need to recalculate head curve coeffs. for all pumps when just a single pump is being assigned a curve with `EN_setheadcurveindex`. It also includes your unit test (with a few small changes made). Let's see if it passes the CI checks.

**Comment by LRossman** [comment]
@AbelHeinsbroek my commit mentioned above passed your test but failed on two others. So clearly I managed to mess up something else. While your fix works OK, I still think it's better to update just the one pump that's being assigned a curve rather than updating all of the other pumps as well when there's no need to do so.

**Comment by AbelHeinsbroek** [comment]
Oops, this was not supposed to be added to the PR but was just for internal testing, let me close this PR.

**Pull request closed without merging**
