### PR TITLE
rm WinSDK folder and update Makefiles

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by Mariosmsk** [comment]
@eladsal, I think it's good to add a file like `win_build.md`, based on the wiki page in folder win_build. https://github.com/OpenWaterAnalytics/EPANET/wiki/Building-the-EPANET-library-and-executable-files
What do you think?

**Comment by eladsal** [comment]
@Mariosmsk yes, good idea

**Comment by eladsal** [comment]
Thanks, ready to merge?

**Comment by Mariosmsk** [comment]
yes! Thanks!

**Comment by eladsal** [comment]
Closes #491

**Comment by eladsal** [comment]
Made a mistake, can't merge now....

**Comment by LRossman** [comment]
I suggest moving the` win_build_md` file up to the root directory, renaming it `BuildNotes.md`, and have it contain the same material that is in the recently updated "How to build EPANET" wiki topic. That way the description of using `CMake` is more visible and is placed in a more appropriate location

**Comment by samhatchett** [comment]
Great idea - I would suggest `BUILDING.md` and provide the Cmake and platform-specific instructions there.

**Comment by Mariosmsk** [comment]
@LRossman , @samhatchett yes I agree.

**Comment by eladsal** [comment]
Just found this older build documentation:
https://github.com/OpenWaterAnalytics/EPANET/blob/dev/.github/BuildAndTest.md

What would you suggest to do with it (strange folder it is in...)?

**Comment by LRossman** [comment]
@eladsal I've also seen that file before. It applies to building the entire project, including the testing infrastructure (thus requiring the Boost libraries). Project contributors or people who just want to build the toolkit don't need to complicate matters by adding the testing protocol on their local machines (I never did). However it does contain useful information for those project administrators tasked with maintaining the testing procedures. Perhaps it could be placed in the tools directory.

**Comment by Mariosmsk** [comment]
I suggest using Table of contents in `README.md` like https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/EMT-2.1.8.1/README.md maybe to avoid many markdown files in the root directory.

**Comment by LRossman** [comment]
I prefer keeping the `README.md` file short and sweet. What's wrong with it referring readers to the wiki pages for information (already in a Table of Contents) on how to build the toolkit and its testing framework, as well as the full API documentation? That would eliminate the need to put these additional `md` files in the project to explain things (and avoid having to issue PRs every time something changes).

**Comment by eladsal** [comment]
I would keep the build&test file in the project. @LRossman suggestion to put it the tools dirctory seems good. Can we agree on that and merge the PR?

**Comment by samhatchett** [comment]
another consideration too, is that the README, and potentially other markdown files in the project top-level are automatically incorporated into the Doxygen build, so everything gets funneled in that way too.

**Comment by LRossman** [comment]
Yes, let's move forward and merge this PR.

**Pull request merged**
