### PR TITLE
Fixed water quality mass balance issue (#160)

### PR DESCRIPTION
**Pull request by LRossman**
The water quality solver was re-written to fix the mass balance issue #160. See the updated ReleaseNotes2_2.md for more details. Also the code that runs a concurrent hydraulic/quality analysis was simplified and tested using this example:
```
// Test of concurrent WQ analysis
#include "epanet2.h"
#include <stdio.h>
int main(int argc, char *argv[])
{
    EN_ProjectHandle ph;
    long t, tstep;
    EN_createproject(&ph);
    EN_open(ph, "net1.inp", "net1a.rpt", "");
    EN_openH(ph);
    EN_initH(ph, 1);
    EN_openQ(ph);
    EN_initQ(ph, 1);
    do {
        EN_runH(ph, &t);
        EN_runQ(ph, &t);
        EN_nextH(ph, &tstep);
        EN_nextQ(ph, &tstep);
    } while (tstep > 0);
    EN_closeH(ph);
    EN_closeQ(ph);
    EN_report(ph);
    EN_close(ph);
}

```

### CODE REVIEW

**Comment by eladsal** [comment]
Thank you @LRossman. In the test you made above, did you compare the results to the full hydraulic and quality runs?

**Comment by michaeltryby** [comment]
@LRossman Nice work!

**Comment by LRossman** [comment]
@eladsal yes, I compared concurrent Net1.inp results against sequential results. There were some small differences in the flow values (like in the 5th - 6th digit) due to the fact that concurrent analysis reports the double floating point value of flow while sequential reads the saved single precision flow from the hydraulics file and then casts it to a double, thus losing some precision. The water quality results were the same when reported to two decimal places.

**Comment by eladsal** [comment]
In `qualroute.c`, line 490, there is an extra semicolon which is causing compiling issues for me :)

**Comment by michaeltryby** [comment]
@LRossman I will be making some commits to your fork to update the regression testing benchmark.

**Comment by LRossman** [comment]
I'm not sure it's necessary but I just wanted to comment on the 4 networks that failed the CI checks.

**Example1.inp (aka Net1.inp):** Over the 24 hr simulation period, one node showed a concentration difference of 0.17 mg/L with the benchmark in just one time period. Otherwise for all nodes in all periods differences were no greater than 0.01 mg/L which was also the quality tolerance used in the analysis.

**Sampletown.inp**: The only differences were for the Newport Tank, which can't be discerned when plotted:
image

**Example3.inp (aka Net3.inp)**: There were some noticeable differences in the Lake trace for this network for a subset of nodes that varied with the time period. A comparison for Node 193 (in the center of the network) looks as follows:
image

The comparison for Node 239 (at the bottom of the network) is shown below:
image

**Simplenet.inp**: there were no differences so I'm not sure why it failed.

**Conclusion**: Because it changes the order in which the nodes of a network are processed, the revised quality routine is expected to show some differences in results from the existing one. Noticeable differences only seem to appear for a small set of nodes at just a few reporting periods. Consistent, systematic differences over the entire network are not occurring, plus the revised routine is producing an error-free mass balance in every network tested so far. I believe that these findings are sufficient to adopt the updated water quality routine as the new benchmark.

**Comment by michaeltryby** [comment]
Interestingly, I'm not able to reproduce these failures on my local machine. I updated the VS install and switched to 32 Bit Python to no avail.

**Comment by michaeltryby** [comment]
@LRossman I'm concerned about the "example3" results. When I diff the report files there are some major differences occurring. What do you attribute this to. Do you have any other water age examples that we can look at?

**Comment by LRossman** [comment]
@michaeltryby I think you meant to say "source tracing" and not "water age" since that is the quality analysis being made in Example3.

In my previous comment I tried to show that the differences for this network occur intermittently at just a few time points. Otherwise the time trajectories match very well. Did you find a node for which this is not the case? We can always look at more networks, but depending on their layout and flow solutions I assume we will still find some that show differences here and there. I would be more concerned if the new implementation was showing consistently different quality trajectories for a significant number of nodes.

Unlike for hydraulics where the mathematical accuracy of the solution can always be tested, there is no way to do the same for water quality (except for trivial examples). Thus you can't say that the 2.0 implementation of the LTD method is "more correct" than the new one. The new one does produce perfect mass balances (it seems like all the time) while the old one doesn't (please read the table in the Improved Water Quality Mass Balance section of the updated Release Notes included with this commit).

Because the new LTD implementation is processing the nodes (and their connected links) from "upstream" to "downstream" order, the mass inflow that a node sees already reflects the transport that occurred for nodes and links upstream of it. This is critically important for nodes at the end of zero-length links (like pumps and valves). It allows the proper amount of mass to be transferred into them, unlike in the current implementation where the mass transferred is based on whatever the upstream node's quality was at the start of the time step. The new LTD implementation is similar in spirit to the way that Kinematic Wave routing is performed in SWMM, where the links have to be processed from upstream to downstream for the results to make physical sense.

**Comment by LRossman** [comment]
Just another note about Example3.net. When run with a 1 sec quality time step there are no longer any differences between results from the current `dev` version and the new commit (except for Tank 1 at hour 5: 0.92% v. 0.93%).

**Comment by michaeltryby** [comment]
@LRossman I built the current epanet dev branch and I built this PR. I changed example3 to a 1 sec WQ time step and ran both versions. You can see from the attached comparison of the binary files that there are more differences than just Tank 1 at hour 5. 

When examining the report files, however, once the initial conditions dissipate the results are within reasonable agreement. I will go ahead and update the benchmark and merge this most excellent PR! Great work!    

[report-diff.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2472990/report-diff.txt)

**Comment by LRossman** [comment]
@michaeltryby the diffs you report have me concerned if we are on the same page. Attached are the two EPANET Report files for Example3 at 1 sec time step that I generated: (1) is for the current dev branch build (before your new merge) and (2) is for my new commit with the modified quality routine. My diff tool only shows the one difference I mentioned previously. Does this merit further investigation?
[example3-rpt.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2473539/example3-rpt.zip)

**Comment by michaeltryby** [comment]
@LRossman How are you building epanet?

**Comment by michaeltryby** [comment]
@LRossman I have attached the example3 report files I'm looking at. 

[example3-tryby.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2473665/example3-tryby.zip)

**Comment by LRossman** [comment]
@michaeltryby mystery solved. I believe you were using a 0:01 (one minute) time step in your comparison instead of 0:00:01 (one second). When I ran my builds with the one minute time step the results exactly matched the report files you provided above. If you change to the 0:00:01 time step I believe you will only see one very small (0.01) diff as I noted earlier.

**Pull request merged**
