### PR TITLE
Changes to get Net1.inp to run

### PR DESCRIPTION
**Pull request by LRossman**

### CODE REVIEW

**Comment by michaeltryby** [comment]
@LRossman Thanks for the PR! Could you tell us a little about the changes you've made? I guess I didn't realize that `Net1.inp` wasn't running.

**Comment by LRossman** [comment]
@michaeltryby To get "dev" to compile I had to initialize `tankVolumes`  in `QUALITY:nextqual()` to `NULL`. But I decided instead to rename it to `QTempVolumes`, make it part of the `quality_t` structure and only allocate memory for it once in `Quality::initqual()` instead of each time that `nextqual()` is called.

Then when trying to run Net1.inp error 305 resulted (could not create hydraulics file), but the error message displayed was "Function call error - Coordinates were not loaded" which of course made no sense. I tracked this down to an incorrect argument passed to `geterrmsg()` in `EPANET:ENgeterror()`. 

Then I discovered that `getTmpNam()` in EPANET.C was creating an illegal file name and was still using the unsafe `tmpnam` function. So I replaced the entire `getTmpNam()` function with the more robust version used in SWMM. After that Net1 ran successfully.

Finally, the compiler also noted that there was no function `writeRuleinInp` which gets called in the INPFILE.C code. That function actually exists in RULES.C but it is declared locally. So I moved the declaration to the FUNCS.H file.

**Comment by michaeltryby** [comment]
@LRossman That sounds great. I'm curious, what compiler are you using?

**Comment by LRossman** [comment]
@michaeltryby Microsoft Visual C++ 2017.

**Comment by michaeltryby** [comment]
@LRossman Oh that's great! We can add Visual Studio 2017 to the Appveyor build matrix.

**Comment by LRossman** [comment]
@michaeltryby Originally built to 32 bit but just compiled it to x64 and it seemed to work OK (at least on net1.inp). With MS VC++ you have to either add `#define _CRT_SECURE_NO_WARNINGS` to each module that uses the `scanf/printf`family of functions or add it to the compiler's pre-processor definitions in the project's settings (which is what I did). Otherwise the compiler flags as errors all lines of code that use those functions.

**Comment by michaeltryby** [comment]
@LRossman I'm going to push a commit to this PR to get Appveyor building on VS 2017 - 64bit and get the reg tests running so we can see where we are with respect to our benchmark. Sound good?

**Comment by michaeltryby** [comment]
@LRossman Sorry about cluttering up your PR :flushed:.  

I got Appveyor building and reg tests running for Visual Studio 2017 Win64: 41 reg tests pass and 4 fail. 

You can see the results [here](https://ci.appveyor.com/project/OpenWaterAnalytics/epanet/build/2.0.42/job/dl4yd5lr89hkg1es). Or by going to the appveyor badge immediately below this post and clicking "details".

**Comment by LRossman** [comment]
@michaeltryby Good job. So where can one find the suite of test files you are running so that the failed tests can be diagnosed?

**Comment by michaeltryby** [comment]
@LRossman in the `tools` folder there is a batch file titled `before-test.cmd` that goes out and grabs the test files and binary benchmark files and stages everything for reg testing. Assuming you don't want to mess with with Python and `nrtest`, you can just browse the batch file and get the gist of what its doing or run it in a command prompt with admin privileges and pass it some dummy arguments. 

If you do want to mess with `nrtest` I can send you more detailed instructions. Just let me know.

**Comment by michaeltryby** [comment]
The input files used for testing can be found [here](https://github.com/OpenWaterAnalytics/epanet-example-networks/archive/v1.0.1.zip).

**Comment by michaeltryby** [comment]
@LRossman Were you going to continue working on this PR to resolve the issues with the failing tests or should I go ahead and merge it? What is your preference?

**Comment by LRossman** [comment]
@michaeltryby I would like to, but the Appveyor results are pretty useless in trying to determine where the discrepancies crop up. For example, here is what was reported for Sampltown.inp:
_mismatch 14.2857142857%)
 x: array([6.825110e+02, 6.825110e+02, 6.025111e+02, 1.500001e+02,
       6.416148e-05, 2.025110e+02, 5.000000e+01])
 y: array([6.825110e+02, 6.825110e+02, 6.025110e+02, 1.500001e+02,
       6.327374e-05, 2.025110e+02, 5.000000e+01])_
I have no idea what these numbers refer to. However you can see that the mis-match occurs for the 5th item whose value is very small (~0.00001) suggesting its a flow in a closed link. I take it these were results using the 64-bit build. Did the 32-bit build pass? How are other contributors going about reconciling Appveyor failures?

**Comment by michaeltryby** [comment]
@LRossman the Appveyor output simply indicates that there is a difference in the Sampletown results. Just like if you ran it as part of your normal testing procedure. I provided the link to the input files so you should have them locally  Run the failing tests locally and dig into the results like you normally would. For engine work it makes sense to run tests locally. That hasn’t changed.

**Comment by lxsinske** [comment]
Hi, also encountered similar differences in results between 64bit and 32bit results when compiling EPANET 2.0.12 a few years ago, and was about to start today to revisiting them. So I'm very interested in following your resolution @LRossman.

**Comment by michaeltryby** [comment]
@lxsinske my understanding is that the shift to 64 bit only affects integer types. We are also porting to a different compiler version which is another potential source of the differences. Reg testing just helps us see these differences more easily.

**Comment by LRossman** [comment]
@michaeltryby Here's what I found regarding the differences in results between various builds of both the current epanet dev branch and my fork, which I'll call dev-1. The latter had only three changes that did not involve any computational portions of the code. (I should note that I had a difficult time using the CMakelists.txt supplied with the dev branch which I will comment on in a separate issue.)

1. You didn't say what compiler was used to produce the 32-bit version of dev that passed the reg tests. I could not get a MSVC build (either 32 or 64-bit) of dev to run because of the illegal file name it generated for the scratch hydraulics file as I mentioned previously and which was one of the issues I fixed in dev-1.
2. Compiling both dev and dev-1 for GNU using cmake produced identical results for the wolf-3.inp file (1985 pipes with 4 pumps and 4 PRVs).
3. Using Makefile.bat to build both a 32- and 64-bit version of dev-1 also produced identical results when each was used to run wolf-3.inp.
4. Using a file comparison tool to compare the flow results from the GNU build of dev (or dev-1 since they produce the same numerical results) with the MSVC build of dev-1 found over 200 differences. Most of these were for values reported as +/- 0.00. Two were for flows through a pump and its connected PRV (1775.73 gpm v. 1775.66 gpm, or < 0.004%). The remaining flow differences were all no larger than 0.01 gpm. The relative flow change for the first six hydraulic trials between the two looked as follows:

GNU Build  | MSVC Build
-----------  | -------------
1.135599   | 1.135599
2.949463   | 2.949467
1.017972   | 1.017972
0.462839   | 0.462842
0.231009   | 0.231007

I'm guessing that the slight differences between results from the GNU build versus the MSVC build is due to differences in the floating point options each compiler uses. MSVC offers three options: fp:precise, fp:fast and fp:strict. The Makefile.bat file did not specify an option so fp:precise was used by default. GNU C++ offers similar sounding options: default, relaxed and full, but uses combinations of six different compiler flags to define these. Changing the floating point options can affect numerical results. I tested this by running dev-1 compiled under MSVC first with fp:precise and then with fp:fast on the wolf-3.inp file. The numerical differences, although not large, were quite noticeable.

**Comment by bemcdonnell** [comment]
@LRossman, for some examples on setting compiler flags for cmake, check out how we did it for SWMM: [SWMM-cmake](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/CMakeLists.txt)

**Comment by bemcdonnell** [comment]
@LRossman, could you clarify which floating point option you were using for GCC? You said there are three but the the configuration is a function of six flags in total. This would be valuable to know for purposes of updating the cmakelists.txt (for swmm too).

**Comment by LRossman** [comment]
@bemcdonnell From [https://gcc.gnu.org/wiki/FloatingPointMath](url) it appears that using the "default" floating point model under GNU C++ doesn't require setting any flags (which would be -fno-rounding-math and -fno-signaling-nans). From [https://stackoverflow.com/questions/3234042/is-there-a-linux-g-equivalent-to-the-fpprecise-and-fpfast-flags-used-in](url) it appears that there is no way to insure 100% floating point equivalence between GNU and MSVC. What I take away from this is that one needs to make automated regression testing dependent on the compiler being used (or relax the difference criteria that signals a failed test).

**Comment by michaeltryby** [comment]
@LRossman Our regression testing IS dependent on the platform and compiler being used. Our current benchmark is Visual Studio 10 2010 32 bit. That is the benchmark currently passing on Appveyor. We run a gcc build on Travis, but we have not done the work to establish a proper benchmark there. The failing tests serve to indicate that Linux is currently unsupported. Due diligence suggests that we identify compiler settings on gcc that minimize platform drift of the results. Wouldn't you agree? However, since this PR contains changes to EPANET to get it building on Visual Studio 15 2017, I don't think gcc is the issue here. Lets set it aside for a moment.   

The issue is that a migration to Windows 64 bit is long overdue. Which version of Visual Studio should we use to do that migration -- Visual Studio 6, 10, 15?  Since this PR gets EPANET building on Visual Studio 15 2017 that seems like as good a place as any to start. Wouldn't you agree? Do you feel confident that the compiler settings you have chosen minimize benchmark drift going from Visual Studio 6 or 10 32 bit -> Visual Studio 15 2017 64 bit? It would really help move the project forward to got out of Visual Studio 6 and 10 and establish a new benchmark on a modern compiler like Visual Studio 15 2017. So hats off to you for getting the ball rolling! 

I will go ahead and create Issues corresponding to the topics raised here to help avoid further confusion. 

Also we are all aware of the learning curve associated with git and CMake.

**Comment by lxsinske** [comment]
I agree to use Visual Studio 15 2017 as basis for EPANET 64 bit, and then confirming that results are near identical to the 32bit EPANET on the same compiler. Should one compare results to the last 32bit EPANET 2.0.12 as well or will changes/fixes introduced in dev and dev-1 make it incompatible?

**Comment by LRossman** [comment]
@lxsinske Resolving issues #160, #164, and #165 (which I plan to work on in the coming weeks) will definitely cause changes in some numerical results from both v. 2.0 and 2.1. I have no idea how this will affect getting PR's approved when the reg tests on these updates will most likely fail.

**Comment by michaeltryby** [comment]
@LRossman It's great that you are going to work on issues #160, #164, and #165!  When you break the reg tests, we can reevaluate and update the benchmark. Shouldn't be a problem :smile:

**Comment by lxsinske** [comment]
@LRossman fixing the zero flow bug will be great! @michaeltryby, maybe a stupid question, but do you already implement a different reg test for 2.1 vs 2.0, or otherwise put, does 2.1 give different numerical results to 2.0 under all or certain conditions?

**Comment by michaeltryby** [comment]
@lxsinske you can find benchmarks [here](https://github.com/OpenWaterAnalytics/epanet-example-networks/releases) The current one is for EPANET v 2.012 VS 10 2010.

**Comment by LRossman** [comment]
Updates were made to the `getTmpName()` in EPANET.C so that the 5 files that failed the initial regression test now produce identical link flow results with those found using EPANET 2.0.012, at least to the two decimal places displayed in the plain text report file, using a 32-bit build under Visual Studio 2017. Also some housekeeping was made to FUNCS.C so that the comments align nicely.

**Comment by michaeltryby** [comment]
@LRossman How was it that `getTmpName()` was causing the regression tests to fail? 

Also, from the CI logs it looks like changing `MAXFNAME` totally broke automated testing.  The `output_api` I wrote has two harmless looking references to it, but it completely breaks all of the tests. Which is kind of interesting.

**Comment by LRossman** [comment]
@michaeltryby I changed the definition of `MAXFNAME` to 260 instead of `L_tmpnam_s` (which isn't really needed here) so please try your automated testing again. Just to repeat, my comparison of flow results with those of 2.0.012 to two decimal places on the 5 files that failed the original test showed no differences using the VS 2017 32-bit compiler.

**Comment by michaeltryby** [comment]
Changed MAXFNAME back to 259 and Visual Studio 2017 from 32 bit. All tests on Appveyor are in the green. This PR is good for merge.

**Pull request merged**
