### PR TITLE
modifies function declarations with unambiguous "out_" prefixes

### PR DESCRIPTION
**Pull request by samhatchett**
... where output parameters are passed. This is a minor change that does not affect the API or any function implementations, but has great benefits to both readability and SWIG-wrapping.

This PR was briefly discussed in #600 and in https://github.com/OpenWaterAnalytics/epanet-python/issues/59

### CODE REVIEW

**Comment by samhatchett** [comment]
anyone have problems with merging this one? thanks!

**Comment by LRossman** [comment]
I'm OK with it.

I'm still curious why the two Travis checks don't show up like they used to (click `Show all checks` to see what I mean).

**Comment by eladsal** [comment]
I'm also fine with it, thanks.

Regarding the Travis checks, it might be an authentication issue were Travis can't right back the results. Do you know with which user is used to grant these permissions?

**Comment by samhatchett** [comment]
I think some things have changed with how travis integrates with GitHub... so might just take some brain cells to figure out

**Pull request merged**
