### PR TITLE
Create Network by chethana

### PR DESCRIPTION
**Pull request by ChethanaUnni**

### CODE REVIEW

**Comment by eladsal** [comment]
@ChethanaUnni this PR has one empty file. Are you going to update it or was this a mistake and can be deleted?

**Comment by ChethanaUnni** [comment]
Please don't delete it. I need it for my thesis work. I will add files to it.

**Comment by samhatchett** [comment]
@ChethanaUnni if you need a space for working on a thesis, please Fork this repo into your personal GitHub account. You can add files, or change anything you want there. PRs for this project should be associated with open issues or bugs. Thanks!

**Comment by samhatchett** [comment]
I should also say (not knowing your intentions here) that if you intend to contribute code into the project, it is best to go through Issues first so that the maintainers and other contributors can discuss first. We just want to avoid sudden and disruptive changes that will negatively affect others.

**Comment by ChethanaUnni** [comment]
Sorry for the inconvenience. I'll delete it.

**Pull request closed without merging**
