### PR TITLE
Fix EN_settankdata for elevation with SI units

### LINKED ISSUE #593: Elevation set incorrectly in EN_settankdata
Elevation is not set correctly with EN_settankdata when metric units are used. This is illustrated with the following:

```
    EN_Project ph = 0;
    int index;
    double required_elevation = 800;
    double retrieved_elevation;

    // Create and initialize project using metric flow units
    EN_createproject(&ph);
    EN_init(ph, "rptfile.rpt", "", EN_CMD, EN_HW);

    // Add a tank
    EN_addnode(ph, "tank", EN_TANK, &index);

    // Set tank data with EN_settankdata and retrieve set value
    EN_settankdata(ph, index, required_elevation, 1, 1, 2, 1, 1, "");
    EN_getnodevalue(ph, index, EN_ELEVATION, &retrieved_elevation);
    fprintf(stdout, "\nretrieved elevation = %f", retrieved_elevation);

    // Set tank data with EN_setnodevalue and retrieve set value
    EN_setnodevalue(ph, index, EN_ELEVATION, required_elevation);
    EN_getnodevalue(ph, index, EN_ELEVATION, &retrieved_elevation);
    fprintf(stdout, "\nretrieved elevation = %f", retrieved_elevation);
```

```
retrieved elevation = 243.840000
retrieved elevation = 800.000000
```

The elevation retrieved after using `EN_settankdata` does not match the value set. If elevation is set using `EN_setnodevalue`, the elevation retrieved afterwards does match that set (as expected).

### PR DESCRIPTION
**Pull request by eladsal**
Fix #593

### CODE REVIEW

**Comment by eladsal** [comment]
@LRossman it is simpler, thanks. Come to think of it, why do we need `elevation` at all, why not just use `elev` where we do the assignment? The same as we do with the other parameters:

>net->Node[Tank[j].Node].El = elev / Ucf[ELEV];
>Tank[j].A = area / Ucf[ELEV] / Ucf[ELEV];
>Tank[j].H0 = (elev+ initlvl) / Ucf[ELEV];
>Tank[j].Hmin = (elev+ minlvl) / Ucf[ELEV];
>Tank[j].Hmax = (elev+ maxlvl) / Ucf[ELEV];

**Comment by LRossman** [comment]
@eladsal any of these code fixes would work. Mine just minimized the number of lines that needed to be changed. Your latest suggestion keeps the updated code more consistent with how other parameters are set, so go ahead and use it if you like -- I'm OK with it.

**Comment by eladsal** [comment]
@LRossman is this last commit fine by you?

**Comment by LRossman** [comment]
@eladsal yes, I approve. Go ahead and merge.

**Pull request merged**
