### PR TITLE
Fixes bug #172 (adjust controls & rules when node/link added or deleted)

### PR DESCRIPTION
**Pull request by LRossman**
- Also adds new API function EN_deletecontrol
- Updates and re-arranges entries in the VBA and VB.Net headers

### CODE REVIEW

**Comment by eladsal** [comment]
@LRossman took a quick look on this merge. Small thing: the function `ENgetstatistic` was deleted from `epanet2.bas` and the new function `ENdeletecontrol` should be added to the `DEF` file.

Big thing: we had a discussion on what to do when deleting elements which are associated with rules and controls, see #240. @samhatchett and I didn't like the "silent deletion" and preferred to give an error. I'm open to hear different opinions but this can't be done with these fast merges.

**Comment by LRossman** [comment]
@eladsal if the code only issues an error message when the API client asks that a node or link appearing in a control or rule should be deleted then I don't see how it can ever actually be deleted. What action would the client take when such an error is generated? The only one I can think of is to delete the controls and/or rules that contain the object to be deleted, and there are no functions for doing that. Even if there were, the node/link indices in the remaining controls would still have to be adjusted manually by the client. Until these steps are taken the object in question cannot properly be deleted.

The actions described above are exactly what my latest commit does. Another alternative that I considered was to replace the index of the deleted object with a 0 in any affected control. That would void   the control without deleting it and without having to make any other code changes. The same would apply to a rule, but to actually make it void something like setting its priority to a negative number could be done which would add just a small amount of new code. However all indices higher than that of the deleted object in all controls and rules would still have to be adjusted. What held me back from implementing this approach was I didn't know how these voided controls and rules should be saved to an INP file.

 Please note that deployment of v.2.2 cannot proceed until this issue is resolved.

**Comment by eladsal** [comment]
@LRossman I really would prefer that we have these discussions before merging the changes.

My thinking, and I think that @samhatchett expressed the same thoughts is #240, is that the client should delete the controls\rules before deleting the elements and if these functions are missing we need to add them (I see you added the control deletion already, thanks). Not sure I like it but what would you say about giving the user a warning that a rule\control was deleted?

> Please note that deployment of v.2.2 cannot proceed until this issue is resolved.

So let us resolve this.

**Comment by samhatchett** [comment]
if we are voting, I would vote again against silently removing link references from controls etc. From a higher "client" level perspective, it's not great to have important features of the data model change without our knowledge or control.

**Comment by LRossman** [comment]
How about re-defining `EN_deletenode` as follows:
```
int EN_deletenode(EN_ProjectHandle ph, int index, int *actioncode);
```
where on input `actioncode `is either `EN_DELETECONTROLS` or` EN_COUNTCONTROLS`. If it's `EN_DELETECONTROLS` then all controls/rules containing the node are deleted as is the node. If it's `EN_COUNTCONTROLS` then on output it contains the number of controls/rules that reference the node. If that number is 0, then the node is deleted. Otherwise no deletion occurs. A similar re-definition for `EN_deletelink` would also be made.

**Comment by samhatchett** [comment]
I think that @LRossman 's suggestion about `EN_DELETECONTROLS` or `EN_COUNTCONTROLS` makes sense if you're using the toolkit directly as an end user - it's pretty intuitive and friendly... 

However (speaking as an application developer), I would prefer an API that didn't let me delete a node unless I first explicitly remove it from the relevant controls. That seems to me more failsafe, since it involves direct action on the things that end up being affected. If I'm putting these actions into an undo stack, then this is also more failsafe, since I have to keep track of what changes were made in case the user changes their mind. If we implicitly remove nodes/links from controls, then there's no record of what they were in order to restore the prior state.

**Comment by LRossman** [comment]
So how about
```
int EN_deletenode(EN_ProjectHandle ph, int index, int *statuscode);
```
where `statuscode `returns as 0 if there were no controls/rules containing the node which will be deleted and otherwise contains the number of controls/rules referencing the node which does not get deleted. Although this same information could be placed in the error code returned by the function I'm afraid that it would get ignored too easily.

I still like my proposal for using an `actioncode `better since if the first call to `EN_deletenode `with `actioncode `set to `EN_COUNTCONTROLS `comes back with a non-zero `actioncode`, and the client decides that it's OK to delete these controls/rules, then a second call to `EN_deletenode `with `actioncode `set to `EN_DELETECONTROLS `will do that in one fell swoop and also delete the node.

Going back to my earlier comment, what recourse does a client have if a node/link they want to delete appears in a control/rule. Either they must delete the control/rule or not delete the node/link. And right now there is no easy way to determine if an object appears in a control/rule. For controls, one has to call `EN_getcontrol `for each control and check its return parameters. For each rule, one has to first call `EN_getrule `to find the number of premise and action clauses, and then repeatedly call `EN_getpremise `and, for links, `EN_gettrueaction `and `EN_getfalseaction `to see if the object appears in the rule. A lot of work just to find out which rules should be deleted (not to mention there is currently no `EN_deleterule `function).

**Comment by eladsal** [comment]
We need a function to delete rules with no relation to this discussion.

I can do with @LRossman `actioncode` proposal. @samhatchett, if you use this option with `EN_COUNTCONTROLS` wouldn't that work for your use case?

**Comment by LRossman** [comment]
Let's summarize the proposed options for dealing with deletion of objects that appear in controls, under the assumption that nobody wants to keep the "silent" control deletion that was just implemented in the latest commit to dev:

1. Keep the declarations of `EN_deletenode` and `EN_deletelink` as they are now but return an error code and don't perform a deletion if the object in question appears in any control (simple or rule-based).

2. Add an action code argument to the two delete functions that on input determines if controls referencing the object will be deleted along with the object or if the number of such controls will be returned in the code with no deletion of either the controls or the object made.

I'm retracting my other proposal for adding a status code argument to the delete functions since it's really no different than option 1. There's a related issue when trying to delete the Trace Node in a water quality analysis. In this case I suggest that both options return an error code and not delete the node when this happens.

Can we reach a decision on which option to implement so we can move forward (I will defer to whatever you all decide). As far as I can tell, this is the last issue that stands in the way of v.2.2 being ready for release.

P.S. @eladsal the latest commit already contains a local function in _rules.c_ that deletes a rule so it will be easy to write an `EN_deleterule(EN_ProjectHandle ph, int ruleIndex)` function that simply calls it.

**Comment by samhatchett** [comment]
thanks for the summary and the discussion. Given all that, I'd still vote for 1 - to error unless the node/link is free of encumbrances. It's not a super heavy lift for an application developer to interrogate the data model to find where the element is referenced.

**Comment by eladsal** [comment]
Option 1 is included in 2, that is you get an indication that the element can't be removed (if you want that). @samhatchett wouldn't that work also for your use case?

**Comment by samhatchett** [comment]
sure, I get it. thinking about it as a "force=true" option helps me to conceptualize. I'm good with this. thanks!

**Comment by eladsal** [comment]
Great, so let's go ahead with the second option.

**Comment by LRossman** [comment]
OK, Option 2 it is. I'll work on it today (and, @eladsal , ask for a code review before merging).

**Comment by LRossman** [comment]
This issue is not quite resolved. When `EN_deletenode `is invoked, even when there are no controls (either  simple or rule-based) that reference the node, it needs to delete the links connected to the node since a link can't exist without having two valid end nodes. So what happens if these links appear in controls? My suggestion is to make the same action code passed in to `EN_deletenode `apply to all of its connecting links. So if the code is `EN_DELETECONTROLS `then both the node and its controls as well as the connecting links and their controls all get deleted. If the code is `EN_COUNTCONTROLS `then the node and its connecting links only get deleted if none of them appear in any control. Otherwise the number of affected controls (by both the node and its connecting links) is returned in the action code and no deletions occur. Is this strategy acceptable?

**Comment by eladsal** [comment]
@LRossman I think it is the right way.

**Comment by eladsal** [comment]
Going over the v2.2 issues I found #239 regarding the trace node when deleting a node.

**Pull request merged**
