### PR TITLE
New function clearreport added (see issue #383)

### PR DESCRIPTION
**Pull request by LRossman**
The newly added `gettitle` and `settitle` functions were moved from the Reporting Functions section to the Project (formerly System) Functions section of epanet2.c and epanet.c.

### CODE REVIEW

**Comment by eladsal** [comment]
@LRossman I may have missed this before but the `win_build` is failing with this error:
`epanet.obj : error LNK2019: unresolved external symbol snprintf referenced in function EN_geterror`

**Comment by LRossman** [comment]
@eladsal I think I see what the problem is:
```
#include "epanet2_2.h"
...
#ifdef WINDOWS
#define snprintf _snprintf
#endif
```
appears at the top of epanet.c, but `WINDOWS` is no longer defined in `epanet2_2.h` . So just replace it with `_WIN32`. I will update `dev` with the fix today.

**Comment by eladsal** [comment]
@LRossman yes, it works, thanks!

**Comment by michaeltryby** [comment]
Close #383

**Pull request merged**
