### PR TITLE
Fixes python wrapper build

### LINKED ISSUE #243: Python wrapper build broken
The current epanet library build configuration breaks the python wrapper build.

### PR DESCRIPTION
**Pull request by michaeltryby**
This PR introduces the preprocessor definition `NO_GENX`. The cmake build has been converted to use genexports while the win_build script has not. `NO_GENX` was added to the win_build script so the cmake build settings do not interfere with it.  

Closes #243

### CODE REVIEW

**Comment by michaeltryby** [comment]
I ran the win_build script and confirmed that it was working. You may, however, need to define `NO_GENX` when you use `epanet2.h` and link with the library.

**Comment by eladsal** [comment]
Not sure why but the build is failing for me:
```
epanet.c(171) : error C2143: syntax error : missing ';' before 'type'
epanet.c(172) : error C2065: 'p' : undeclared identifier
epanet.c(172) : error C2223: left of '->viewprog' must point to struct/union
epanet.c(174) : error C2065: 'p' : undeclared identifier
epanet.c(174) : error C2223: left of '->out_files' must point to struct/union
```

**Comment by michaeltryby** [comment]
@eladsal what compiler are you using?

**Comment by eladsal** [comment]
The one that comes with the SDK:
`Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01`

I think it is a C89 issue.

**Comment by michaeltryby** [comment]
@eladsal you are using Visual Studio 2010. The rest of the project has upgraded to Visual Studio 2017.

**Comment by michaeltryby** [comment]
I got it to build locally using Visual Studio 2010.

**Comment by eladsal** [comment]
@michaeltryby not sure about "rest of the project...". Do you know what is the way to switch the compiler without installing VS (I don't have VS 2010 installed)?

**Comment by michaeltryby** [comment]
I'm going to go ahead and merge this PR.

**Comment by eladsal** [comment]
@michaeltryby yes, I'm not going to install VS at the moment, thanks.

**Pull request merged**
