### PR TITLE
Add a cron schedule in actions per month to create artifacts 

### PR DESCRIPTION
**Pull request by Mariosmsk**

### CODE REVIEW

**Comment by eladsal** [comment]
Thank you @Mariosmsk 

The reasoning for this commit is that the Artifacts' retention policy is 90 days at most so the compiled DLLs are gone if we don't push anything within this period.

**Comment by samhatchett** [comment]
Just asking because I'm curious - why does anyone need to access the artifacts?

**Comment by eladsal** [comment]
@samhatchett, the artifacts are the compiled DLLs for the different environments. This is the only place people can access them without compiling the code and they are update for every commit.

**Comment by samhatchett** [comment]
@eladsal thanks, i see. why not use Releases for that access?

**Comment by eladsal** [comment]
At least back then releases were not compiling automatically the DLLs with every push.

**Comment by eladsal** [comment]
Thanks @Mariosmsk

**Pull request merged**
