### PR TITLE
Re-write of main.c (issue #355)

### PR DESCRIPTION
**Pull request by LRossman**

### CODE REVIEW

**Comment by LRossman** [comment]
The CI tests failed the 12 reg test files whose runs generated warning messages. This commit changes the way these messages appear on both the console and in the Status Report creating a mis-match with the current benchmarks and thus causing the failures. Performing the tests locally "by hand" showed no differences in computed results. It is requested that new benchmarks be posted for the following files so that this commit can be merged:
2fcvs.inp  5fcvs.inp  anytown-3.inp  exnet-3.inp  exnet-3H.inp  exnet-3Q.inp  mod_anytown-3.inp
simpson_test.inp  simpson_test_2-12.inp  st-net3.inp  test101.inp  test101-3.inp

**Comment by michaeltryby** [comment]
@LRossman Looking over the Appveyor Log it appears that the executable built from this PR is failing to run for a significant number of the tests. It is generating failures and non-zero exit codes while generating test benchmarks. The reg test isn't progressing to the second stage where the comparisons occur. There may be a problem with the code that you should investigate. Thanks!

**Comment by LRossman** [comment]
@michaeltryby I have tested the code built as a command line executable with the current cmake script (which I did not alter). It runs just fine, but the console output is different from the current benchmark in that it displays an alert if a run has warnings generated. The 12 files that fail the CI tests all run with warnings (such as negative pressures, insufficient pump head, etc.) under both the existing version of dev and under this new commit. To reiterate, there are no coding errors in this commit. The CI test is failing because the console output now includes an alert if the run generated warning messsages (something which v.2.0 always did but is now absent in 2.2).

**Comment by michaeltryby** [comment]
@LRossman This PR changes the semantics of the return value from main. It has always returned 0 even when the simulation produced warnings or errors. These warnings and errors are produced in the course of "normal" operation of EPANET. They are essentially handled exceptions. The return value from main should be reserved for errors and failures that aren't being handled. 

The framework I use to execute the reg tests `nrtest` expects a zero when the program exits normally. This isn't something I can change easily. While on the other hand, having `runepanet()` return 0 is a trivial change. So I would prefer the later. Seems like a fair compromise to me.

**Comment by michaeltryby** [comment]
Here is more information about exit status. 

https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html

**Comment by LRossman** [comment]
In the last commit comment, I meant to say `errcode `and not `errmsg`.

**Pull request merged**
