### PR TITLE
Removed some compiler warnings

### PR DESCRIPTION
**Pull request by jburguete**

### CODE REVIEW

**Comment by LRossman** [comment]
I suggest that the autoconf scripts be removed from this PR. This is an addition that should be posted as an issue so that the project's community can present their views on it.

**Comment by samhatchett** [comment]
I agree with @LRossman on the autoconf addition. the project is standardized on CMake, which generates build files. changes to that strategy should be discussed more fully

**Comment by jburguete** [comment]
I agree also.
Sorry, I am not yet familiarized with git branches.
I did not wanted the second commit here but in my account fork.

**Comment by samhatchett** [comment]
feel free to resubmit after removing the autoconf additions 👍

**Pull request closed without merging**
