### PR TITLE
Require rpt file

### PR DESCRIPTION
**Pull request by bradleyjeck**
Dear Maintainers,

The changes in this PR were made to pass checks required of compiled C code in R packages. I submit it here for possible inclusion in the next release of EPANET.

Compiled C code in R packages shouldn't write to stdout.

I completely understand if allowing reporting to stdout is the preferred behavior. Feel free to reject the PR in that case.

### CODE REVIEW

**Comment by michaeltryby** [comment]
Any objections to merging this?

**Comment by samhatchett** [comment]
reporting to `stdout` should still be an option - do the R checks fail if there's _any_ reference to `stdout`, or can we put it in a conditional where console output is non-default but accessible through an api call?

**Comment by bradleyjeck** [comment]
A conditional might work.  If you'll show me what it looks like I don' mind trying it.

**Comment by samhatchett** [comment]
It just occurred to me though, since the package gets compiled separately for the R package, what about having a compile-time conditional? So compile with, for instance, `-DNO_STDOUT=1` for the R distribution, or for anyone who wants that.

**Comment by bradleyjeck** [comment]
I can test that and see if R complains.  Commenting out a couple of lines
in the R version is also an option :)

**Comment by samhatchett** [comment]
closing in favor of #188

**Pull request closed without merging**
