### PR TITLE
SWIG wrapper development

### LINKED ISSUE #110: Add SWIG interface generators
requires some special handling for opaque pointers:
https://github.com/swig/swig/wiki/FAQ#q-how-do-i-interact-with-functions-that-require-double-void-pointers---void-

... but will let us do python-based testing more easily and also build better downstream python abstractions with less complicated dependencies.

### PR DESCRIPTION
**Pull request by michaeltryby**
This PR includes the following changes: 
- separation of cmakelist.txt for library and run targets 
- changes to epanet library for SWIG wrap
    EN_Project is now void* EN_ProjectHandle 
    improved error management for in wrapper exception generation
- Unit testing for toolkit

Closes #110 

The Python side of this work can be found [here](https://github.com/OpenWaterAnalytics/epanet-python/tree/dev).

### CODE REVIEW

**Comment by michaeltryby** [comment]
This PR is building now.

**Comment by michaeltryby** [comment]
Any objections to merging this?

**Comment by eladsal** [comment]
Thanks. Why do we need another directory? The util one?

**Comment by michaeltryby** [comment]
@eladsal the code for the `errormanager` is shared between `epanet` and `epanet-output` libraries. Since it it gets used in both places, rather than duplicating it, it makes sense to put it in its own place and have the libraries refer to it. Organizing it this way also fits with Issue #123.

**Comment by michaeltryby** [comment]
@eladsal 👌  Be my guest and push the changes for the win build script here. Thanks!

**Comment by bemcdonnell** [comment]
@eladsal, I think @michaeltryby is doing a nice job leading by example with respect to the contributing workflow.  If a line of code is added, it is to your benefit and the greater community that it is accompanied by testing (unit, regression, or hybrid).  Therefore, Michael's test is here in this PR because he added new code to benefit the greater good.  If there were a checklist of "to do before committing" it would be something like the following:

### Open Source Software Development Workflow
1. raise and issue and discuss the change with the community (before writing code)
2. write the code
3. add documentation (if possible / required)
4. write the tests to test the new code
5. submit a pull request
6. get approval
7. merge and 
...
8. repeat until the codebase is *perfect*

With respect to the targeted build tools that are inside this repository (win build script), how come there isn't a convergence to use `cmake`?  A clean project does not contain esoteric - user-specific build scripts.  For example, I have 5 different configurations to build SWMM and I just keep them around locally so I can run them.  There is no need for them to be under version control.  Aside from convenience, is there any reason this project needs to have specific build files just "laying around"?  Collaborative repositories should contain general and user-agnostic codes/scripts.  

In addition, how come everyone hasn't converged to running reg tests / unit tests, locally?  I believe these fundamental building blocks in modern open source software development.  When you work in a distributed development workflow everyone should be running the same tests.  This way, we can all police ourselves and we **do not need a central person or entity to rubber stamp anything.**  I think some groups collaborating on SWMM and EPANET are completely missing the boat here - if we standardize the testing, then it doesn't matter. 

This isn't a rant (I have no skin in this particular game).  I just feel that the OpenWaterAnalytics projects should be treated as first class citizens.   The better these projects are treated, the more successful they will become.  :-)

**Comment by michaeltryby** [comment]
@bemcdonnell I appreciate your support and the spirit in which you posted this. But I don't think its that helpful. Elad has contributed a lot to the project and he can adopt the practices that make sense for him.

**Comment by eladsal** [comment]
@bemcdonnell,

My "tests" comment was meant to say that they are not related to this PR (probably most of them). This PR is for #110 (Add SWIG interface generators). How does adding test for simultaneous stepping through hyd and qual simulation (a93465e1ccaf16a9c333a2cf8ed1bf4d088fce43) relates to SWIG? The test is very important but not related. BTW, if you look back in this repo you will find that I wrote the first testing scripts. Since this is a big PR I just commented that the unrelated test code can have its own PR.

I am thankful that @michaeltryby and others contribute code to benefit the greater good. I don't care why they do it. As for myself, I do like to help others but the main reason is that EPANET is one of my working tools (we work for the same company, don't we?) and there are things I need changed, features added, bug fixed and so on... I figure that if I contribute I would benefit from the contributions of others. Egoistic, right? Well, I find the win build scripts much easier to work with, one click and you are done. It is also very easy to install and for new comers. Only today we saw that other people use it and for a tool all EPANET-Matlab users work with. So I took it upon myself to maintain the script and if it kept in the repo it is simpler.

@michaeltryby would you like me to push the small unrelated fixes for #231 and #232 ?

**Comment by michaeltryby** [comment]
@eladsal I’ve found it’s helpful to unit test an api and be certain that it’s working as intended prior to wrapping it. That’s why testing is included in the PR. Please issue a separate

**Comment by eladsal** [comment]
1602e5b corrupted `Makefile.bat`. Will fix.

**Comment by michaeltryby** [comment]
Oops!

**Comment by michaeltryby** [comment]
@eladsal Sorry about that.

**Comment by eladsal** [comment]
@michaeltryby no worries, easy fix. where should I push it to, here?

**Comment by michaeltryby** [comment]
This PR is closed now. Let's open a new PR and then we can sort out #232 and some other odds and ends as well.

**Pull request merged**
