### PR TITLE
adds api support for enabling/disabling controls and rules

### PR DESCRIPTION
**Pull request by samhatchett**
As discussed long ago in the Issues tracker. I've added old-style api stubs as well for this functionality.

### CODE REVIEW

**Review by LRossman — COMMENTED** [review]
The new code looks OK but I would prefer that the new control/rule property be declared as:
```
int isEnabled;
```
and use the already defined TRUE (= 1) and FALSE (= 0) constants as its value. I think that's a more natural way of treating what is a boolean condition. Whether you switch to this or stay with ENABLED/DISABLED you should add the following constants to epanet2_enums.h:
```
typedef enum {
    EN_DISABLED = 0,
    EN_ENABLED = 1
} EN_EnabledType;
```
or
```
#define EN_FALSE 0
#define EN_TRUE 1
```

**Comment by samhatchett** [comment]
@LRossman thanks for the comments. I agree with using the existing int/bool conventions - makes everything a bit clearer. I'll clean this up.

**Review by LRossman — APPROVED** [review]
Nice job. Everything looks OK.

A suggestion for a future enhancement is to have an input file include a control/rule's enabled status. If ENABLED is the default then this can be done by attaching the keyword DISABLED to the end of a control statement or on a separate line at the end of a rule.

**Comment by eladsal** [comment]
Thanks @samhatchett !
We need to add the four new functions to the different header files (pas\vb\def), right? I can probably do that next week if nobody will do that before :)

**Comment by samhatchett** [comment]
@eladsal sure, sounds good. I'm not as familiar with the pas/vb/def particulars so am happy to leave that in your capable hands. ok to merge this PR then, or would you prefer to wait on those additions?

**Comment by eladsal** [comment]
@samhatchett yes I'll take care of it. Maybe just update `ReleaseNotes2_3.md` before you merge.

**Review by eladsal — APPROVED** [review]

**Pull request merged**
