### PR TITLE
Improved Node Re-Ordering Method (Issue #162)

### PR DESCRIPTION
**Pull request by LRossman**
The original Minimum Degree (MD) node re-ordering method used when solving the linearized set of hydraulic equations was replaced with the more powerful Multiple Minimum Degree (MMD) method. This resulted in reducing steady state hydraulic solution times by an average of more than 50% for eight test networks as seen in the following table:

Network | # Junctions | MMD/MD Time
-------- | ------------ | -------------- |
1           |   7,699        |  0.736
2           |   8,566        | 0.396 
3           |  14,991       | 0.311
4           |  27,006       | 0.486
5           |  28,899       | 0.618
6           |  33,247       | 0.278
7           |  42,664       | 0.400
8           |  100,235     | 0.154

The timings used for MMD and MD were processor times monitored between `createsparse()` and `freesparse()` in SMATRIX.C using the C` clock()` function.

Manual regression testing against 21 of the EPANET benchmark networks did show some flow differences in 7 networks. These tended to be no larger than 0.001 flow units, with the first 5 to 6 digits matching in most all cases. It should be noted that because of the approximate nature of floating point arithmetic, simply running EPANET 2.00.12 on the same network with the junctions listed in a different order will produce slightly different flow results than for the original network, with differences of the same order as found here for the MMD-to-MD comparison tests.

### CODE REVIEW

**Comment by michaeltryby** [comment]
@LRossman Great work!

**Comment by michaeltryby** [comment]
@LRossman I've been working in QA'ing your PR. I've developed a new comparison routine that computes the minimum correct decimal digits for a binary file comparison. I'm still testing it, but I've discovered some irregularities in the binary files using it - what were previously zeros are now replaced with a number. I will dig into it more and email you what I find.

**Comment by LRossman** [comment]
If computed flows `Q` and heads `H` change between versions then so will the computed friction factor `f` saved to the binary output file since it depends on these quantities:
```
h = ABS(H[Link[i].N1] - H[Link[i].N2]);
f = 39.725*h*pow(Link[i].Diam,5)/Link[i].Len/SQR(Q[i]);
```
I want to emphasize again that even under 2.00.12, placing the nodes in a different order in the input file will cause results to be slightly different. Test the two versions of NW_Model in [NW_Model.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2181988/NW_Model.zip), where NW_Model_r.inp lists junctions in reverse order from NW_Model.inp, running both under 2.00.12 to verify this. I'm surprised that after all these years no one has seemed to point this out or complain about it.

Also, I'm not sure if having the internally computed double precision results cast to single precision before being saved to the binary results file has any impact on the numerical differences being seen.

**Comment by michaeltryby** [comment]
@LRossman The results in the binary file actually do a round trip. They start out as double, get cast to float and written to the binary file. Then they get read from the binary file as a float and cast to a double since python floating point objects are equivalent to a double in C lang. 

If you are only concerned with 3 decimal places of precision, then casting from double to float and float to double should not make a difference.

**Comment by michaeltryby** [comment]
@LRossman Here is a log of the differences found between epanet-2012 and this branch for example2 based on log relative error. LRE is analogous to correct significant digits. 

The Idx field is as follows: 
Idx: (element index, (element type, time period index, element attribute))
Sut - Software Under Test (i.e. the code in this PR)
Ref - Is the benchmark value

[diff-report.log](https://github.com/OpenWaterAnalytics/EPANET/files/2186232/diff-report.log)

**Comment by LRossman** [comment]
@michaeltryby thanks for the more informative diff-report. However, as I've stated before, similarly small differences in results will occur running the same build (2.0.012, 2.1, 2.2 etc.) twice on the same file whose ordering of items in the [JUNCTIONS] section of the input file is changed. This is strictly a numerical accuracy phenomenon and I don't know how to avoid it, except perhaps by using long doubles (which is not a standard data type across all machines and compilers) for all linear algebra calculations.

I suggest we get a consensus from other members of the development team if the doubling of speed with the new node re-ordering routine is worth sacrificing some numerical consistency (which, like I keep saying, can occur even with the current EPANET release).

**Comment by michaeltryby** [comment]
@LRossman sounds good. Let’s open it up for some discussion.

**Comment by michaeltryby** [comment]
If a tree falls in a forest and no one is around to hear it, does it make a sound?

**Comment by dickinsonre** [comment]
LRE: 1.591065
Idx: (7, (<ElementType.LINK: 2>, 44, <LinkAttribute.FRCTN_FCTR: 8>))
Sut: 0.033111
Ref: 0.032283

Sorry for my ignorance, but what is LRE?  Sut and Ref look close for the most of the items in your log file,  it would help to the see the relative difference between Sut and Ref

**Comment by michaeltryby** [comment]
LRE stands for Log Relative Error. The code used to generate diff log can be found [here](https://github.com/michaeltryby/EPANET/blob/dev-test/tools/nrtest-epanet/report_diff.py)

**Comment by eladsal** [comment]
@michaeltryby this looks very similar to the two years old test scripts I'm using which are still on the `master` branch [here](https://github.com/OpenWaterAnalytics/EPANET/tree/master/tests/scripts/vb6_binary_files_compare) (see the readme file).

**Comment by michaeltryby** [comment]
@LRossman I finished QAing the PR. It checks out like you say. I'm going to go ahead and append some commits here updating the benchmark then I will merge.

**Comment by michaeltryby** [comment]
Close #162 

The benchmark has been updated. Tests on Appveyor 32 bit are passing. Travis CI is operational but failing. 

This PR is good for merge.

**Pull request merged**
