### PR TITLE
Dev list

### LINKED ISSUE #452: make list management easier with a generic reusable list
Working on the memory leaks in the `netbuilder API` it occurred to me that many are occurring in lists. The lists in EPANET are raw data structures linked together. This makes working with them problematic. 

One solution would be a generic reusable linked list with an API that makes managing lists easier. I found one [here](https://pseudomuto.com/2013/05/implementing-a-generic-linked-list-in-c/) that I think will do nicely.

### LINKED ISSUE #460: API needs EN_adddemand and EN_deletedemand functions
To allow the API to completely build a full EPANET model just using function calls requires that two new functions be added that will create and delete demand categories at junction nodes. Without these networks built with the API will be limited to using just a single demand catgeory at each junction.

### PR DESCRIPTION
**Pull request by michaeltryby**
This PR introduces a generic reusable list. The list has an easy to use API for creating, deleting, and iterating. Moreover, the list abstraction is completely encapsulated and inaccessible from the rest of the application. 

This PR uses the generic list to re-implement the demand lists associated with node structs. Previously demand lists were allocated when no demands were present at a node, now they are lazy initialized. 

This PR demonstrates the advantages of unit testing and test driven development. The generic list and demand data structs were tested as separate units prior to being integrated with the application. Then tests were written to target areas where the new code was tied in with the old.  

I am pleased with how this PR turned out. The only problem was it took longer to prepare than I anticipated. 

Close #452
Close #460

### CODE REVIEW

**Comment by LRossman** [comment]
I found a few things that may need to be changed:

1. `strdup` used in `create_demand_data` isn't part of standard C.
2. The `_adjustpattern` function name in _project.c_ violates best practice of not using an underscore to begin a name. I'm also not a fan of starting a mnemonic like `lnode` with a lower case L since it looks too much like the number one (`listnode `would be better).
3. Assigning `DefPatID` to junction demands as they are read from the input file will be a problem if the `DefPatID` hasn't been established yet (which is usually the case since the [JUNCTIONS] and [DEMANDS] sections typically precede the [OPTIONS] section in an INP file). It's better to return to the original code where the default pattern is assigned after the entire input file has been read.
4. In `EN_getnodevalue` and `EN_setnodevalue`, the `EN_BASEDEMAND `and `EN_PATTERN `properties are for the node's primary demand which is the first demand specified. Shouldn't they be the demands at the head of the list, not the tail?

**Comment by michaeltryby** [comment]
Thanks for the feedback.

**Comment by LRossman** [comment]
It also seems that, contrary to the way that demand categories were originally stored, this new generic list approach is keeping two copies of each demand category. One generated by `create_demand_data` and a copy of it created by the `append_list` function (lines 89 - 93 of _list.c_). Why is a copy of the list data being made for each list node. Can't the node just store the pointer for the demand data passed into `append_list`. Or alternatively, couldn't the demand data structure passed into `append_list ` be declared locally on the stack (which would also eliminate the need to define a `freeFunction `for the list)?

**Comment by michaeltryby** [comment]
@LRossman in this list implementation the data are held via double pointers. In the append and prepend list function memcpy is used to copy the pointer to the data not the data itself.

**Comment by michaeltryby** [comment]
The beauty of this design is that it is completely encapsulated from the rest of the application. Thus, it can be refactored, and as long as the "contract" that is the API is satisfied the application still works. 

I agree that the use of `memcpy` is unusual. But the "proof is in the pudding" as they say. This code passes all unit tests and has no memory leaks. The `free_function` is necessary for the list to be generic and re-usable. I intend to reuse it!

**Comment by michaeltryby** [comment]
@LRossman Question pertaining to point 4 in your review. 

If base demand is the head node in the demand list why are for loops that appear to be returning the tail of the list being used in `EN_getnodevalue()` and `EN_setnodevalue()`?

**Comment by LRossman** [comment]
@michaeltryby in the original implementation of the demand list, new demands were added to the head, not the tail, of the list when they were read from the input file. Somewhere along the way this was changed to do the opposite (see lines 755 - 767 of _input3.c_ in the latest version of dev) but apparently `EN_getnodevalue()` and `EN_setnodevalue()` weren't updated to reflect this change.

**Comment by michaeltryby** [comment]
@LRossman thanks for the info. The implementation I am proposing in this PR uses the `append_list()` function to add nodes to a demand list -- meaning that new nodes are added at the tail of this list. The first node added will be the head, the last node added will be the tail, and the nodes will appear in the order they were added. Is this the behavior that you prefer?

**Comment by LRossman** [comment]
@michaeltryby yes, that's the preferable (and more natural) order.

**Comment by michaeltryby** [comment]
@LRossman Okay. Then it follows that `EN_getnodevalue()` and `EN_setnodevalue()` should return the head of the list if one assumes that the primary demand gets added first.  I will update the PR accordingly.

**Comment by michaeltryby** [comment]
@LRossman Addressed the points you raised in your review. On point 1, strdup is present on Windows, Linux, and Mac OS so in my estimation it's portable. I don't know why MSVC complains about it. 

Points 2, 3, and 4 have been resolved.

**Comment by LRossman** [comment]
Replacement for `strdup` in `create_demand_data` (see [this discussion](https://stackoverflow.com/questions/32944390/what-is-the-rationale-for-not-including-strdup-in-the-c-standard)):
```
demand_data_t *create_demand_data(double base_demand, int pattern_index, const char *category_name)
{
    demand_data_t *demand_data = (demand_data_t *)malloc(sizeof(demand_data_t));

    demand_data->base_demand = base_demand;
    demand_data->pattern_index = pattern_index;

    if (category_name)
    {
        size_t size = strlen(category_name) + 1;
        char *p = malloc(size);
        if (p) memcpy(p, category_name, size);
        demand_data->category_name = p;
    }
    else
        demand_data->category_name = NULL;

    return demand_data;
}
```
Or if `xstrcpy `(in _project.c_) were made visible:
```
demand_data_t *create_demand_data(double base_demand, int pattern_index, const char *category_name)
{
    demand_data_t *demand_data = (demand_data_t *)malloc(sizeof(demand_data_t));

    demand_data->base_demand = base_demand;
    demand_data->pattern_index = pattern_index;
    demand_data->category_name = NULL;
    xstrcpy(&demand_data->category_name, category_name, MAXID);

    return demand_data;
}
```

**Comment by michaeltryby** [comment]
Oh, I’ve already got a replacement for strdup in my cstr_helper module.

**Comment by michaeltryby** [comment]
Interesting article. As far as I know, there are no plans to use third party memory allocation solutions. I’m really tired of the limitation imposed by fixed length char arrays so I have been experimenting.

**Comment by michaeltryby** [comment]
Added key values to list nodes and added search for key values. This is a much better way to provide random access to list elements. Also added method for removing list nodes based on key. So now we have everything we need to implement #460.

**Comment by LRossman** [comment]
@michaeltryby thanks for adding these functions. Are you going to merge with OWA::dev shortly? I have commits ready for #464 and am willing to implement #460. Or is more time needed for further testing (one test I'd like to see is a run time comparison between the new and old list methods on a network with a significant number of demand categories).

**Comment by michaeltryby** [comment]
Actually I'm in the middle of finishing up #460 as I type this. 

You are welcome to create a PR for Issue #464. I can fetch pull the changes in no problem.

**Comment by michaeltryby** [comment]
Kinda tired of working on this. So I'm going to merge.

**Comment by michaeltryby** [comment]
When you say significant number of demand categories what number do you have in mind? More or less than 100? 

This list is essentially doing the same thing that the old lists did. I suspect the difference is going to be in the memory usage not CPU time. I have tried to offset memory usage by shifting to lazy initialization of the demand lists in the node structs. 

Suppose we could write a test_case for this.

**Pull request merged**
