### PR TITLE
Improved modeling of tank dynamics - 2 (Issue #165)

### PR DESCRIPTION
**Pull request by LRossman**
The explicit Euler integration scheme for EPS was replaced with an implicit one resulting in more stable results for tank levels. More details can be found in the updated v. 2.2 Release Notes. This update will fail any reg tests that are EPS since the implicit scheme will produce similar but not identical tank level results. It might also fail some of the single period tests since tanks are now included in the hydraulic solver's matrix equations. This will produce a different ordering and number of elementary algebraic operations when the equations are solved -- similar to the situation that occurred when the node re-ordering method was replaced for Issue #162.

### CODE REVIEW

**Comment by michaeltryby** [comment]
Great job @LRossman!  

I am going to push to your branch to resolve these merge conflicts and update the benchmarks.

**Comment by eladsal** [comment]
@michaeltryby can you give us a little time to run some networks to look at results before you merge and update the benchmarks?

**Comment by LRossman** [comment]
Hold everything. I just received some real-world files to test from Jacek Blaszczyk that are failing to run under the new implicit scheme due to an ill-conditioned matrix. This points out the difference between using simple test examples from research papers versus real-world networks. We need to look into why his networks are failing (they run OK under the old method) before committing this update. I will keep you informed.
P.S. I still don't know how to cancel a PR.

**Comment by michaeltryby** [comment]
Actually Lew, you don’t have to close it. You can fix the bug and append your changes to it. Just do a
git push origin contributor-lr 
And your new commits will be automatically added to the PR.

**Comment by LRossman** [comment]
Here's an update on why the implicit tank scheme was resulting in an ill-conditioned solution matrix for Jacek's model. Under this scheme, after time 0, tanks appear as variable (unknown) head nodes in the solution matrix. Any connecting pipes add an off-diagonal coefficient to the matrix whose value is the reciprocal of their head loss derivative at the current flow. At very low flows this coefficient becomes extremely large, which was the case for several tanks in Jacek's network and is the apparent cause of the ill-conditioning.

It should be noted that at time 0 and for the explicit method, the tanks are always fixed grade and the coefficients from their connecting pipes appear on the RHS of the linearized model thus not affecting the condition of the model's matrix. I've also done some testing with other more well-behaved networks where the implicit method seemed to work OK.

Issue #164 deals with avoiding numerical issues with low or zero flows. I propose that this issue be addressed next to see if it allows the implicit tank dynamics method to be successful on Jacek's network.

**Comment by michaeltryby** [comment]
So would you like to merge this PR or leave it as is while you work on #164?

**Comment by LRossman** [comment]
@michaeltryby after doing more testing with implicit tank dynamics I am not satisfied with how it is performing:

- For some longer term EPS runs where the network results should enter into a repeating pattern the implicit method is not producing a similar response (since it's not possible to predict exactly when within the next time step a tank-based control will kick in).

- In some cases  where a tank hits its maximum level the implicit method gets stuck and doesn't allow the tank to start emptying again (the methods in the literature for handling full tanks assume that they will spill any excess flow while EPANET has always assumed that the tank has an altitude valve which stops any inflow once it becomes full).

Therefore I've decided that the implicit method is not yet ready for prime time and so as not to delay things I am closing this PR.

**Pull request closed without merging**
