### PR TITLE
Eliminates use of temporary linked lists to process Patterns & Curves…

### PR DESCRIPTION
**Pull request by LRossman**
… (issue #449)

### CODE REVIEW

**Comment by Mariosmsk** [comment]
@LRossman, bug in EN_getcurvetype when I call index 2 for the test INP file `BWSN_Network_1.inp` `(return -2147483648)`

**Comment by LRossman** [comment]
@Mariosmsk I don't have the `BWSN_Network_1.inp` file. Could you send me a link to it or maybe post it in a response as a zipped file. Thanks.

**Comment by Mariosmsk** [comment]
[BWSN_Network_1.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3049284/BWSN_Network_1.zip)

**Comment by LRossman** [comment]
@Mariosmsk it's been fixed. Thanks for testing it.

**Comment by Mariosmsk** [comment]
@LRossman, It's ok. Now returns the code type GENERAL but is the PUMP!

**Comment by LRossman** [comment]
@Mariosmsk the curve with index 2 is named CURVE-1. Although the comment attached to it says its a pump curve, if you search the BWSN_Network_1 file you will see that it's not used by any of the pumps, which is how the toolkit determines if a curve is a pump curve or not. Therefore it's designated as a EN_GENERIC_CURVE.

**Comment by Mariosmsk** [comment]
@LRossman, yes. So it's ok. Thanks!

**Pull request merged**
