### PR TITLE
Floating pt. args in thread-safe API changed to doubles (Issue #365)

### PR DESCRIPTION
**Pull request by LRossman**
This commit addresses Issue #365 by converting all of the floating point arguments from `EN_API_FLOAT_TYPE` to` double`. In the process, a lot of clean-up was done to the API function declarations in both `epanet2.h` and` epanet2_2.h` to use identical argument names between the two sets of functions and to make the names more descriptive. Also, the doxygen documentation comments were moved from the legacy API header file `epanet2.h` into the new thread-safe API header `epanet2_2.h`, since that is the API that will be emphasized going forward. (A comment was added to the top of `epanet2.h` saying that each function's documentation could be found in the corresponding function of `epanet2_2.h`)

### CODE REVIEW

**Comment by eladsal** [comment]
@LRossman thank you. I have marked the VB reserved words in variable names with an ending "_". Also, I don't see the previous options to get the pump `state` and the `price_pattern`. We had those options awhile ago and they seems to got removed along the way...

**Comment by LRossman** [comment]
@eladsal good catch on the VB keywords. Pump state and price pattern are symbolized as `EN_PUMP_STATE` and `EN_PUMP_EPAT` and are included in `EN_getlinkvalue`. `EN_PUMP_STATE` is a "read-only" variable and therefore it is not included in `EN_setlinkvalue`. `EN_PUMP_ECOST` was missing from `EN_getlinkvalue` so I added it in my latest commit. I also re-arranged the cases in the switch statement of both `EN_getlinkvalue` and `EN_setlinkvalue` so they follow the same order used for the contents of the `EN_LinkProperty` enumeration.

**Comment by eladsal** [comment]
@LRossman I don't know how but we managed to drop some code we already had. See tag `v2.2.0-dev.4` and the [`epanet.c`](https://github.com/OpenWaterAnalytics/EPANET/blob/v2.2.0-dev.4/src/epanet.c) file. We had the `EN_PRICEPATTERN` option and also `EN_SPEED` (which now I don't see).

**Comment by eladsal** [comment]
That is fine, just wanted to understand the changes. Thanks.

**Comment by michaeltryby** [comment]
Close Issue #365

**Comment by michaeltryby** [comment]
@LRossman this PR introduced several build errors on the Travis Linux build and the reentrancy test is failing. 

https://travis-ci.org/OpenWaterAnalytics/EPANET

**Comment by LRossman** [comment]
@michaeltryby I rebuilt the project under 64-bit Ubuntu Linux. There were warnings but no errors. Next I did a sanity check against net1.inp -- all results were the same as for 32-bit Windows. Then I re-wrote the threading test to use OpenMP instead of Boost. It worked just fine with no seg faults. 
test_reent2
The first run above is with OpenMP disabled while the second has it enabled.

[test_reent2.cpp.zip](https://github.com/OpenWaterAnalytics/EPANET/files/2770319/test_reent2.cpp.zip)

**Pull request merged**
