### PR TITLE
Toolkit API Housekeeping 

### PR DESCRIPTION
**Pull request by michaeltryby**
This PR separates EN* from EN_* API functions and places them into v2.1 and v2.2 header and implementation files respectively. It's a little different than what you are used to, but I think it's an improvement. 

For example, if we want to do a build targeting a specific version of the API, this PR makes it straight forward. If we want to deprecate an older version of the API, it can easily be communicated to library users by updating the export macro. Or if we choose to retire a version of the API that process is simplified as well. What do you think? 

Issue #333

### CODE REVIEW

**Comment by michaeltryby** [comment]
Close Issue #330

**Comment by LRossman** [comment]
@michaeltryby could you please hold off on merging this commit until I have a chance to merge the updates I made to fix #172 plus adding the new `EN_addrule `function. I am close to committing these updates for review (possibly by tomorrow). Otherwise I'm afraid I will have to either start from square one again or have to resolve a gazillion conflicts.

Also would it be possible to simply name the headers _epanet2.1.h_ and _epanet2.2.h_ (_epanet2_dep_ is not very descriptive - some may think _dep_ stands for _deprecated_).

**Comment by LRossman** [comment]
Sorry, I didn't notice the merge branch at the top of the page. And after viewing the new header files I see that _dep_ actually does stand for deprecated (aka v.2.1).

I have some comments/questions on what you're proposing. It seems like the v2.2 functions are being declared twice in the new epanet2.h. Also, for clients who want to run the _dep_ version (2.1) they have to add both header files (_epanet2_dev.h_ and _epanet2.h_) to their projects even though they will only use the functions in epanet2_dev.h. An alternative would be to remove the enumerations from _epanet2.h_ and put them in a separate header (maybe named _epanet_enums.h_). Then clients add this header plus the one for the API version they want to use into their projects.

**Comment by michaeltryby** [comment]
@LRossman thanks for your feedback. I’m not sure if you are looking at the complete set of commits I’m proposing. Do a git fetch, git pull to make sure you have them all. 

It is true that the epanet_2_1.h includes epanet_2_2.h to share enums. Since the v2.1 api has been implemented using v2.2 it is difficult to completely separate them. 

Also I would like to mark the v2.1 API for deprecation, but thought better of it.

**Comment by LRossman** [comment]
@michaeltryby let me expand further on my idea (we may be splitting hairs here, but humor me). Three header files get distributed with the API library: _epanet2_enums.h, epanet2-1.h_ and _epanet2_2.h_.
_Epanet2_enums.h_ defines all of the enumerated values used by the API plus the following line:
```
typedef struct Project *EN_Project;
```
The latter refers to the project wrapper where it's defined in _types.h_ as:
```
typedef struct Project {
    <existing code>
} Project, *EN_Project;
```
_Epanet2_1.h_ contains declarations of the 2.1 API:
```
#include "epanet2_enums.h"
int DLLEXPORT ENxxx(...);
etc.
```
_Epanet2_2.h_ contains declarations of the 2.2 API:
```
#include "epanet2_enums.h"
int DLLEXPORT EN_xxx(Project p, ...);
etc.
```
As for _epanet2_1.c_, it's contents look as follows:
```
#include "epanet2_1.h"
#include "epanet2_2.h"
EN_Project _defaultProject;
int DLLEXPORT ENxxx(...) {
    return EN_xxx(_defaultProject, ...);
}
etc.
```
And _epanet2_2.c_ has the format:
```
#include "epanet2_2.h"
int DLLEXPORT EN_xxx(EN_Project p, ...) {
    <code>
}
etc.
```
API clients need only include _epanet2_1.h_ in their code if they want to use the 2,1 API or _epanet2_2.h_ to use the 2.2 library. Note that instead of using a void pointer as a handle to the Project wrapper (and having to recast it in every API function) we use an opaque pointer to the Project struct which I think makes life simpler (I have tested this in the existing code base and it works just fine).

**Comment by michaeltryby** [comment]
@LRossman I follow what you are saying right up to the void pointer. The void pointer and an opaque pointer are one and the same. The idea is to prevent the client from accessing the contents of EN_Project directly. That is why a void pointer is used. However, since it has proven unpopular. I'm fine with rolling it back.

**Comment by LRossman** [comment]
@michaeltryby in our case using the typed project pointer will not expose the contents of `EN_Project` to an API client since those contents are defined in _types.h_ which the client never sees.

**Comment by michaeltryby** [comment]
@LRossman I don't want to belabor the point, just state the facts for the record. A motivated client can copy the struct definition for EN_Project from `types.h` and access it's members via the project pointer. With a void pointer the client can not do this because the client code will malfunction if they do. Moreover, if we make a change to EN_Project struct the client code will need to be recompiled. With a void pointer the client is isolated from changes to the project pointer. Therefore, a void pointer provides better isolation of the library code from the client than using a pointer to EN_Project does.

**Comment by LRossman** [comment]
@michaeltryby I believe you're mistaken in saying that client code has to be recompiled when a typed project pointer is used instead of a void pointer. As long as the `typedef `used in the API header matches the one used in _types.h_ it can be used as an argument in a client's API function calls no matter what changes have been made to the `struct` it points to since it always gets de-referenced in the library code, not the client's code.

**Comment by michaeltryby** [comment]
@LRossman I believe you are mistaken [Opaque Pointers](https://en.wikipedia.org/wiki/Opaque_pointer).

**Comment by LRossman** [comment]
@michaeltryby that doesn't address my argument. Think it through and tell me where I'm wrong.

**Comment by michaeltryby** [comment]
Hey @LRossman thanks for the feedback. I was in the middle of doing precisely what you suggested as you were suggesting it. :smile:

**Pull request closed without merging**
